// Mocks generated by Mockito 5.4.6 from annotations
// in free_cal_counter1/test/providers/food_search_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:free_cal_counter1/models/food.dart' as _i2;
import 'package:free_cal_counter1/models/food_unit.dart' as _i5;
import 'package:free_cal_counter1/services/database_service.dart' as _i3;
import 'package:free_cal_counter1/services/open_food_facts_service.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFood_0 extends _i1.SmartFake implements _i2.Food {
  _FakeFood_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i3.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.Food>> searchFoodsByName(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchFoodsByName, [query]),
            returnValue: _i4.Future<List<_i2.Food>>.value(<_i2.Food>[]),
          )
          as _i4.Future<List<_i2.Food>>);

  @override
  _i4.Future<List<_i5.FoodUnit>> getUnitsForFood(_i2.Food? food) =>
      (super.noSuchMethod(
            Invocation.method(#getUnitsForFood, [food]),
            returnValue: _i4.Future<List<_i5.FoodUnit>>.value(<_i5.FoodUnit>[]),
          )
          as _i4.Future<List<_i5.FoodUnit>>);

  @override
  _i4.Future<_i2.Food?> getFoodByBarcode(String? barcode) =>
      (super.noSuchMethod(
            Invocation.method(#getFoodByBarcode, [barcode]),
            returnValue: _i4.Future<_i2.Food?>.value(),
          )
          as _i4.Future<_i2.Food?>);

  @override
  _i4.Future<_i2.Food?> getFoodBySourceFdcId(int? fdcId) =>
      (super.noSuchMethod(
            Invocation.method(#getFoodBySourceFdcId, [fdcId]),
            returnValue: _i4.Future<_i2.Food?>.value(),
          )
          as _i4.Future<_i2.Food?>);

  @override
  _i4.Future<_i2.Food> saveFood(_i2.Food? food) =>
      (super.noSuchMethod(
            Invocation.method(#saveFood, [food]),
            returnValue: _i4.Future<_i2.Food>.value(
              _FakeFood_0(this, Invocation.method(#saveFood, [food])),
            ),
          )
          as _i4.Future<_i2.Food>);
}

/// A class which mocks [OffApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOffApiService extends _i1.Mock implements _i6.OffApiService {
  MockOffApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Food?> fetchFoodByBarcode(String? barcode) =>
      (super.noSuchMethod(
            Invocation.method(#fetchFoodByBarcode, [barcode]),
            returnValue: _i4.Future<_i2.Food?>.value(),
          )
          as _i4.Future<_i2.Food?>);
}
