// Mocks generated by Mockito 5.4.6 from annotations
// in free_cal_counter1/test/providers/search_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:io' as _i8;

import 'package:free_cal_counter1/models/category.dart' as _i13;
import 'package:free_cal_counter1/models/daily_macro_stats.dart' as _i12;
import 'package:free_cal_counter1/models/food.dart' as _i3;
import 'package:free_cal_counter1/models/food_portion.dart' as _i10;
import 'package:free_cal_counter1/models/food_serving.dart' as _i9;
import 'package:free_cal_counter1/models/food_usage_stats.dart' as _i14;
import 'package:free_cal_counter1/models/logged_portion.dart' as _i11;
import 'package:free_cal_counter1/models/recipe.dart' as _i2;
import 'package:free_cal_counter1/services/database_service.dart' as _i4;
import 'package:free_cal_counter1/services/food_sorting_service.dart' as _i6;
import 'package:free_cal_counter1/services/open_food_facts_service.dart' as _i5;
import 'package:free_cal_counter1/services/search_service.dart' as _i15;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i16;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRecipe_0 extends _i1.SmartFake implements _i2.Recipe {
  _FakeRecipe_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFood_1 extends _i1.SmartFake implements _i3.Food {
  _FakeFood_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseService_2 extends _i1.SmartFake
    implements _i4.DatabaseService {
  _FakeDatabaseService_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOffApiService_3 extends _i1.SmartFake implements _i5.OffApiService {
  _FakeOffApiService_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFoodSortingService_4 extends _i1.SmartFake
    implements _i6.FoodSortingService {
  _FakeFoodSortingService_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i4.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> restoreDatabase(_i8.File? backupFile) =>
      (super.noSuchMethod(
            Invocation.method(#restoreDatabase, [backupFile]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i3.Food>> searchFoodsByName(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchFoodsByName, [query]),
            returnValue: _i7.Future<List<_i3.Food>>.value(<_i3.Food>[]),
          )
          as _i7.Future<List<_i3.Food>>);

  @override
  _i7.Future<List<_i9.FoodServing>> getServingsForFood(
    int? foodId,
    String? foodSource,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getServingsForFood, [foodId, foodSource]),
            returnValue: _i7.Future<List<_i9.FoodServing>>.value(
              <_i9.FoodServing>[],
            ),
          )
          as _i7.Future<List<_i9.FoodServing>>);

  @override
  _i7.Future<Map<int, List<_i9.FoodServing>>> getServingsForFoods(
    List<int>? foodIds,
    String? foodSource,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getServingsForFoods, [foodIds, foodSource]),
            returnValue: _i7.Future<Map<int, List<_i9.FoodServing>>>.value(
              <int, List<_i9.FoodServing>>{},
            ),
          )
          as _i7.Future<Map<int, List<_i9.FoodServing>>>);

  @override
  _i7.Future<String?> getLastLoggedUnit(int? originalFoodId) =>
      (super.noSuchMethod(
            Invocation.method(#getLastLoggedUnit, [originalFoodId]),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<_i3.Food?> getFoodByBarcode(String? barcode) =>
      (super.noSuchMethod(
            Invocation.method(#getFoodByBarcode, [barcode]),
            returnValue: _i7.Future<_i3.Food?>.value(),
          )
          as _i7.Future<_i3.Food?>);

  @override
  _i7.Future<_i3.Food?> getFoodBySourceFdcId(int? fdcId) =>
      (super.noSuchMethod(
            Invocation.method(#getFoodBySourceFdcId, [fdcId]),
            returnValue: _i7.Future<_i3.Food?>.value(),
          )
          as _i7.Future<_i3.Food?>);

  @override
  _i7.Future<void> logPortions(
    List<_i10.FoodPortion>? portions,
    DateTime? logTimestamp,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#logPortions, [portions, logTimestamp]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool> isRecipeLogged(int? recipeId) =>
      (super.noSuchMethod(
            Invocation.method(#isRecipeLogged, [recipeId]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> isRecipeUsedAsIngredient(int? recipeId) =>
      (super.noSuchMethod(
            Invocation.method(#isRecipeUsedAsIngredient, [recipeId]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<void> hideRecipe(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#hideRecipe, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i11.LoggedPortion>> getLoggedPortionsForDate(
    DateTime? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLoggedPortionsForDate, [date]),
            returnValue: _i7.Future<List<_i11.LoggedPortion>>.value(
              <_i11.LoggedPortion>[],
            ),
          )
          as _i7.Future<List<_i11.LoggedPortion>>);

  @override
  _i7.Future<int> saveFood(_i3.Food? food) =>
      (super.noSuchMethod(
            Invocation.method(#saveFood, [food]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<void> deleteLoggedPortion(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLoggedPortion, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteLoggedPortions(List<int>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLoggedPortions, [ids]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateLoggedPortion(
    int? loggedPortionId,
    _i10.FoodPortion? newPortion,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateLoggedPortion, [
              loggedPortionId,
              newPortion,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateLoggedPortionsTimestamp(
    List<int>? loggedPortionIds,
    DateTime? newTimestamp,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateLoggedPortionsTimestamp, [
              loggedPortionIds,
              newTimestamp,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i12.LoggedMacroDTO>> getLoggedMacrosForDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLoggedMacrosForDateRange, [start, end]),
            returnValue: _i7.Future<List<_i12.LoggedMacroDTO>>.value(
              <_i12.LoggedMacroDTO>[],
            ),
          )
          as _i7.Future<List<_i12.LoggedMacroDTO>>);

  @override
  _i7.Future<_i3.Food?> getFoodById(int? id, String? source) =>
      (super.noSuchMethod(
            Invocation.method(#getFoodById, [id, source]),
            returnValue: _i7.Future<_i3.Food?>.value(),
          )
          as _i7.Future<_i3.Food?>);

  @override
  _i7.Future<List<_i2.Recipe>> getRecipes({bool? includeHidden = false}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecipes, [], {#includeHidden: includeHidden}),
            returnValue: _i7.Future<List<_i2.Recipe>>.value(<_i2.Recipe>[]),
          )
          as _i7.Future<List<_i2.Recipe>>);

  @override
  _i7.Future<List<_i2.Recipe>> getRecipesBySearch(
    String? query, {
    int? categoryId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getRecipesBySearch,
              [query],
              {#categoryId: categoryId},
            ),
            returnValue: _i7.Future<List<_i2.Recipe>>.value(<_i2.Recipe>[]),
          )
          as _i7.Future<List<_i2.Recipe>>);

  @override
  _i7.Future<_i2.Recipe> getRecipeById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getRecipeById, [id]),
            returnValue: _i7.Future<_i2.Recipe>.value(
              _FakeRecipe_0(this, Invocation.method(#getRecipeById, [id])),
            ),
          )
          as _i7.Future<_i2.Recipe>);

  @override
  _i7.Future<List<_i13.Category>> getCategoriesForRecipe(int? recipeId) =>
      (super.noSuchMethod(
            Invocation.method(#getCategoriesForRecipe, [recipeId]),
            returnValue: _i7.Future<List<_i13.Category>>.value(
              <_i13.Category>[],
            ),
          )
          as _i7.Future<List<_i13.Category>>);

  @override
  _i7.Future<int> saveRecipe(_i2.Recipe? recipe) =>
      (super.noSuchMethod(
            Invocation.method(#saveRecipe, [recipe]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<void> deleteRecipe(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRecipe, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i13.Category>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i7.Future<List<_i13.Category>>.value(
              <_i13.Category>[],
            ),
          )
          as _i7.Future<List<_i13.Category>>);

  @override
  _i7.Future<int> addCategory(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#addCategory, [name]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<_i3.Food> ensureFoodExists(_i3.Food? food) =>
      (super.noSuchMethod(
            Invocation.method(#ensureFoodExists, [food]),
            returnValue: _i7.Future<_i3.Food>.value(
              _FakeFood_1(this, Invocation.method(#ensureFoodExists, [food])),
            ),
          )
          as _i7.Future<_i3.Food>);

  @override
  _i7.Future<Map<int, String?>> getFoodsUsageNotes(List<_i3.Food>? foods) =>
      (super.noSuchMethod(
            Invocation.method(#getFoodsUsageNotes, [foods]),
            returnValue: _i7.Future<Map<int, String?>>.value(<int, String?>{}),
          )
          as _i7.Future<Map<int, String?>>);

  @override
  _i7.Future<_i3.Food> copyFoodToLiveDb(
    _i3.Food? sourceFood, {
    bool? isCopy = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #copyFoodToLiveDb,
              [sourceFood],
              {#isCopy: isCopy},
            ),
            returnValue: _i7.Future<_i3.Food>.value(
              _FakeFood_1(
                this,
                Invocation.method(
                  #copyFoodToLiveDb,
                  [sourceFood],
                  {#isCopy: isCopy},
                ),
              ),
            ),
          )
          as _i7.Future<_i3.Food>);

  @override
  _i7.Future<void> softDeleteFood(int? foodId, String? source) =>
      (super.noSuchMethod(
            Invocation.method(#softDeleteFood, [foodId, source]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool> isFoodReferenced(int? foodId, String? source) =>
      (super.noSuchMethod(
            Invocation.method(#isFoodReferenced, [foodId, source]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<void> deleteFood(int? foodId, String? source) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFood, [foodId, source]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i3.Food>> searchLiveFoodsByName(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchLiveFoodsByName, [query]),
            returnValue: _i7.Future<List<_i3.Food>>.value(<_i3.Food>[]),
          )
          as _i7.Future<List<_i3.Food>>);

  @override
  _i7.Future<List<_i3.Food>> searchReferenceFoodsByName(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchReferenceFoodsByName, [query]),
            returnValue: _i7.Future<List<_i3.Food>>.value(<_i3.Food>[]),
          )
          as _i7.Future<List<_i3.Food>>);

  @override
  _i7.Future<Map<int, _i14.FoodUsageStats>> getFoodUsageStats(
    List<int>? foodIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFoodUsageStats, [foodIds]),
            returnValue: _i7.Future<Map<int, _i14.FoodUsageStats>>.value(
              <int, _i14.FoodUsageStats>{},
            ),
          )
          as _i7.Future<Map<int, _i14.FoodUsageStats>>);

  @override
  _i7.Future<Map<int, _i14.FoodUsageStats>> getRecipeUsageStats(
    List<int>? recipeIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getRecipeUsageStats, [recipeIds]),
            returnValue: _i7.Future<Map<int, _i14.FoodUsageStats>>.value(
              <int, _i14.FoodUsageStats>{},
            ),
          )
          as _i7.Future<Map<int, _i14.FoodUsageStats>>);

  @override
  _i7.Future<bool> isRecipeReferenced(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#isRecipeReferenced, [id]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<List<_i3.Food>> filterReferenceFoodsWithLiveVersions(
    List<_i3.Food>? referenceFoods,
    List<_i3.Food>? liveFoods,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#filterReferenceFoodsWithLiveVersions, [
              referenceFoods,
              liveFoods,
            ]),
            returnValue: _i7.Future<List<_i3.Food>>.value(<_i3.Food>[]),
          )
          as _i7.Future<List<_i3.Food>>);
}

/// A class which mocks [OffApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOffApiService extends _i1.Mock implements _i5.OffApiService {
  MockOffApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i3.Food?> fetchFoodByBarcode(String? barcode) =>
      (super.noSuchMethod(
            Invocation.method(#fetchFoodByBarcode, [barcode]),
            returnValue: _i7.Future<_i3.Food?>.value(),
          )
          as _i7.Future<_i3.Food?>);

  @override
  _i7.Future<List<_i3.Food>> searchFoodsByName(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchFoodsByName, [query]),
            returnValue: _i7.Future<List<_i3.Food>>.value(<_i3.Food>[]),
          )
          as _i7.Future<List<_i3.Food>>);
}

/// A class which mocks [SearchService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchService extends _i1.Mock implements _i15.SearchService {
  MockSearchService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.DatabaseService get databaseService =>
      (super.noSuchMethod(
            Invocation.getter(#databaseService),
            returnValue: _FakeDatabaseService_2(
              this,
              Invocation.getter(#databaseService),
            ),
          )
          as _i4.DatabaseService);

  @override
  _i5.OffApiService get offApiService =>
      (super.noSuchMethod(
            Invocation.getter(#offApiService),
            returnValue: _FakeOffApiService_3(
              this,
              Invocation.getter(#offApiService),
            ),
          )
          as _i5.OffApiService);

  @override
  String Function(String) get emojiForFoodName =>
      (super.noSuchMethod(
            Invocation.getter(#emojiForFoodName),
            returnValue: (String __p0) => _i16.dummyValue<String>(
              this,
              Invocation.getter(#emojiForFoodName),
            ),
          )
          as String Function(String));

  @override
  _i6.FoodSortingService get sortingService =>
      (super.noSuchMethod(
            Invocation.getter(#sortingService),
            returnValue: _FakeFoodSortingService_4(
              this,
              Invocation.getter(#sortingService),
            ),
          )
          as _i6.FoodSortingService);

  @override
  _i7.Future<List<_i3.Food>> searchLocal(String? query, {int? categoryId}) =>
      (super.noSuchMethod(
            Invocation.method(#searchLocal, [query], {#categoryId: categoryId}),
            returnValue: _i7.Future<List<_i3.Food>>.value(<_i3.Food>[]),
          )
          as _i7.Future<List<_i3.Food>>);

  @override
  _i7.Future<List<_i3.Food>> searchOff(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchOff, [query]),
            returnValue: _i7.Future<List<_i3.Food>>.value(<_i3.Food>[]),
          )
          as _i7.Future<List<_i3.Food>>);

  @override
  _i7.Future<List<_i3.Food>> getAllRecipesAsFoods({int? categoryId}) =>
      (super.noSuchMethod(
            Invocation.method(#getAllRecipesAsFoods, [], {
              #categoryId: categoryId,
            }),
            returnValue: _i7.Future<List<_i3.Food>>.value(<_i3.Food>[]),
          )
          as _i7.Future<List<_i3.Food>>);

  @override
  _i7.Future<List<_i3.Food>> searchRecipesOnly(
    String? query, {
    int? categoryId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchRecipesOnly,
              [query],
              {#categoryId: categoryId},
            ),
            returnValue: _i7.Future<List<_i3.Food>>.value(<_i3.Food>[]),
          )
          as _i7.Future<List<_i3.Food>>);
}
