// Mocks generated by Mockito 5.4.6 from annotations
// in free_cal_counter1/test/widgets/log_header_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i3;

import 'package:free_cal_counter1/providers/navigation_provider.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [NavigationProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationProvider extends _i1.Mock
    implements _i2.NavigationProvider {
  MockNavigationProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get selectedIndex =>
      (super.noSuchMethod(Invocation.getter(#selectedIndex), returnValue: 0)
          as int);

  @override
  bool get shouldFocusSearch =>
      (super.noSuchMethod(
            Invocation.getter(#shouldFocusSearch),
            returnValue: false,
          )
          as bool);

  @override
  bool get showConsumed =>
      (super.noSuchMethod(Invocation.getter(#showConsumed), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setShowConsumed(bool? value) => super.noSuchMethod(
    Invocation.method(#setShowConsumed, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void changeTab(int? index) => super.noSuchMethod(
    Invocation.method(#changeTab, [index]),
    returnValueForMissingStub: null,
  );

  @override
  void goToSearch() => super.noSuchMethod(
    Invocation.method(#goToSearch, []),
    returnValueForMissingStub: null,
  );

  @override
  void goToDataManagement() => super.noSuchMethod(
    Invocation.method(#goToDataManagement, []),
    returnValueForMissingStub: null,
  );

  @override
  void resetSearchFocus() => super.noSuchMethod(
    Invocation.method(#resetSearchFocus, []),
    returnValueForMissingStub: null,
  );

  @override
  void goBack() => super.noSuchMethod(
    Invocation.method(#goBack, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i3.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i3.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
