// Mocks generated by Mockito 5.4.6 from annotations
// in free_cal_counter1/test/widgets/search_ribbon_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;
import 'dart:ui' as _i14;

import 'package:free_cal_counter1/models/daily_macro_stats.dart' as _i2;
import 'package:free_cal_counter1/models/food.dart' as _i13;
import 'package:free_cal_counter1/models/food_portion.dart' as _i9;
import 'package:free_cal_counter1/models/goal_settings.dart' as _i6;
import 'package:free_cal_counter1/models/logged_portion.dart' as _i10;
import 'package:free_cal_counter1/models/macro_goals.dart' as _i7;
import 'package:free_cal_counter1/models/recipe.dart' as _i11;
import 'package:free_cal_counter1/models/search_mode.dart' as _i18;
import 'package:free_cal_counter1/providers/goals_provider.dart' as _i19;
import 'package:free_cal_counter1/providers/log_provider.dart' as _i8;
import 'package:free_cal_counter1/providers/navigation_provider.dart' as _i15;
import 'package:free_cal_counter1/providers/search_provider.dart' as _i16;
import 'package:free_cal_counter1/services/database_service.dart' as _i3;
import 'package:free_cal_counter1/services/open_food_facts_service.dart' as _i4;
import 'package:free_cal_counter1/services/search_service.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i17;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDailyMacroStats_0 extends _i1.SmartFake
    implements _i2.DailyMacroStats {
  _FakeDailyMacroStats_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseService_1 extends _i1.SmartFake
    implements _i3.DatabaseService {
  _FakeDatabaseService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOffApiService_2 extends _i1.SmartFake implements _i4.OffApiService {
  _FakeOffApiService_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSearchService_3 extends _i1.SmartFake implements _i5.SearchService {
  _FakeSearchService_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoalSettings_4 extends _i1.SmartFake implements _i6.GoalSettings {
  _FakeGoalSettings_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMacroGoals_5 extends _i1.SmartFake implements _i7.MacroGoals {
  _FakeMacroGoals_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LogProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogProvider extends _i1.Mock implements _i8.LogProvider {
  MockLogProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  double get loggedCalories =>
      (super.noSuchMethod(Invocation.getter(#loggedCalories), returnValue: 0.0)
          as double);

  @override
  double get queuedCalories =>
      (super.noSuchMethod(Invocation.getter(#queuedCalories), returnValue: 0.0)
          as double);

  @override
  double get queuedProtein =>
      (super.noSuchMethod(Invocation.getter(#queuedProtein), returnValue: 0.0)
          as double);

  @override
  double get queuedFat =>
      (super.noSuchMethod(Invocation.getter(#queuedFat), returnValue: 0.0)
          as double);

  @override
  double get queuedCarbs =>
      (super.noSuchMethod(Invocation.getter(#queuedCarbs), returnValue: 0.0)
          as double);

  @override
  double get queuedFiber =>
      (super.noSuchMethod(Invocation.getter(#queuedFiber), returnValue: 0.0)
          as double);

  @override
  double get totalCalories =>
      (super.noSuchMethod(Invocation.getter(#totalCalories), returnValue: 0.0)
          as double);

  @override
  double get totalProtein =>
      (super.noSuchMethod(Invocation.getter(#totalProtein), returnValue: 0.0)
          as double);

  @override
  double get totalFat =>
      (super.noSuchMethod(Invocation.getter(#totalFat), returnValue: 0.0)
          as double);

  @override
  double get totalCarbs =>
      (super.noSuchMethod(Invocation.getter(#totalCarbs), returnValue: 0.0)
          as double);

  @override
  double get totalFiber =>
      (super.noSuchMethod(Invocation.getter(#totalFiber), returnValue: 0.0)
          as double);

  @override
  double get dailyTargetCalories =>
      (super.noSuchMethod(
            Invocation.getter(#dailyTargetCalories),
            returnValue: 0.0,
          )
          as double);

  @override
  double get dailyTargetProtein =>
      (super.noSuchMethod(
            Invocation.getter(#dailyTargetProtein),
            returnValue: 0.0,
          )
          as double);

  @override
  double get dailyTargetFat =>
      (super.noSuchMethod(Invocation.getter(#dailyTargetFat), returnValue: 0.0)
          as double);

  @override
  double get dailyTargetCarbs =>
      (super.noSuchMethod(
            Invocation.getter(#dailyTargetCarbs),
            returnValue: 0.0,
          )
          as double);

  @override
  double get dailyTargetFiber =>
      (super.noSuchMethod(
            Invocation.getter(#dailyTargetFiber),
            returnValue: 0.0,
          )
          as double);

  @override
  List<_i9.FoodPortion> get logQueue =>
      (super.noSuchMethod(
            Invocation.getter(#logQueue),
            returnValue: <_i9.FoodPortion>[],
          )
          as List<_i9.FoodPortion>);

  @override
  List<_i10.LoggedPortion> get loggedPortion =>
      (super.noSuchMethod(
            Invocation.getter(#loggedPortion),
            returnValue: <_i10.LoggedPortion>[],
          )
          as List<_i10.LoggedPortion>);

  @override
  bool get isFasted =>
      (super.noSuchMethod(Invocation.getter(#isFasted), returnValue: false)
          as bool);

  @override
  Set<int> get selectedPortionIds =>
      (super.noSuchMethod(
            Invocation.getter(#selectedPortionIds),
            returnValue: <int>{},
          )
          as Set<int>);

  @override
  bool get hasSelectedPortions =>
      (super.noSuchMethod(
            Invocation.getter(#hasSelectedPortions),
            returnValue: false,
          )
          as bool);

  @override
  int get selectedPortionCount =>
      (super.noSuchMethod(
            Invocation.getter(#selectedPortionCount),
            returnValue: 0,
          )
          as int);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void addFoodToQueue(_i9.FoodPortion? serving) => super.noSuchMethod(
    Invocation.method(#addFoodToQueue, [serving]),
    returnValueForMissingStub: null,
  );

  @override
  void addRecipeToQueue(_i11.Recipe? recipe, {double? quantity = 1.0}) =>
      super.noSuchMethod(
        Invocation.method(#addRecipeToQueue, [recipe], {#quantity: quantity}),
        returnValueForMissingStub: null,
      );

  @override
  void dumpRecipeToQueue(_i11.Recipe? recipe, {double? quantity = 1.0}) =>
      super.noSuchMethod(
        Invocation.method(#dumpRecipeToQueue, [recipe], {#quantity: quantity}),
        returnValueForMissingStub: null,
      );

  @override
  void updateFoodInQueue(int? index, _i9.FoodPortion? newPortion) =>
      super.noSuchMethod(
        Invocation.method(#updateFoodInQueue, [index, newPortion]),
        returnValueForMissingStub: null,
      );

  @override
  void removeFoodFromQueue(_i9.FoodPortion? serving) => super.noSuchMethod(
    Invocation.method(#removeFoodFromQueue, [serving]),
    returnValueForMissingStub: null,
  );

  @override
  void clearQueue() => super.noSuchMethod(
    Invocation.method(#clearQueue, []),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> refreshFoodInQueue(int? foodId, _i13.Food? updatedFood) =>
      (super.noSuchMethod(
            Invocation.method(#refreshFoodInQueue, [foodId, updatedFood]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> logQueueToDatabase() =>
      (super.noSuchMethod(
            Invocation.method(#logQueueToDatabase, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> loadLoggedPortionsForDate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#loadLoggedPortionsForDate, [date]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> toggleFasted(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFasted, [date]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> deleteLoggedPortion(_i10.LoggedPortion? food) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLoggedPortion, [food]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> updateLoggedPortion(
    _i10.LoggedPortion? oldLoggedPortion,
    _i9.FoodPortion? newPortion,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateLoggedPortion, [
              oldLoggedPortion,
              newPortion,
            ]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<List<_i2.DailyMacroStats>> getDailyMacroStats(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDailyMacroStats, [start, end]),
            returnValue: _i12.Future<List<_i2.DailyMacroStats>>.value(
              <_i2.DailyMacroStats>[],
            ),
          )
          as _i12.Future<List<_i2.DailyMacroStats>>);

  @override
  _i12.Future<_i2.DailyMacroStats> getTodayStats() =>
      (super.noSuchMethod(
            Invocation.method(#getTodayStats, []),
            returnValue: _i12.Future<_i2.DailyMacroStats>.value(
              _FakeDailyMacroStats_0(
                this,
                Invocation.method(#getTodayStats, []),
              ),
            ),
          )
          as _i12.Future<_i2.DailyMacroStats>);

  @override
  void togglePortionSelection(int? portionId) => super.noSuchMethod(
    Invocation.method(#togglePortionSelection, [portionId]),
    returnValueForMissingStub: null,
  );

  @override
  void selectPortion(int? portionId) => super.noSuchMethod(
    Invocation.method(#selectPortion, [portionId]),
    returnValueForMissingStub: null,
  );

  @override
  void deselectPortion(int? portionId) => super.noSuchMethod(
    Invocation.method(#deselectPortion, [portionId]),
    returnValueForMissingStub: null,
  );

  @override
  void clearSelection() => super.noSuchMethod(
    Invocation.method(#clearSelection, []),
    returnValueForMissingStub: null,
  );

  @override
  bool isPortionSelected(int? portionId) =>
      (super.noSuchMethod(
            Invocation.method(#isPortionSelected, [portionId]),
            returnValue: false,
          )
          as bool);

  @override
  void copySelectedPortionsToQueue() => super.noSuchMethod(
    Invocation.method(#copySelectedPortionsToQueue, []),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> moveSelectedPortions(DateTime? newTimestamp) =>
      (super.noSuchMethod(
            Invocation.method(#moveSelectedPortions, [newTimestamp]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> deleteSelectedPortions() =>
      (super.noSuchMethod(
            Invocation.method(#deleteSelectedPortions, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NavigationProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationProvider extends _i1.Mock
    implements _i15.NavigationProvider {
  MockNavigationProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get selectedIndex =>
      (super.noSuchMethod(Invocation.getter(#selectedIndex), returnValue: 0)
          as int);

  @override
  bool get shouldFocusSearch =>
      (super.noSuchMethod(
            Invocation.getter(#shouldFocusSearch),
            returnValue: false,
          )
          as bool);

  @override
  bool get showConsumed =>
      (super.noSuchMethod(Invocation.getter(#showConsumed), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setShowConsumed(bool? value) => super.noSuchMethod(
    Invocation.method(#setShowConsumed, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void changeTab(int? index) => super.noSuchMethod(
    Invocation.method(#changeTab, [index]),
    returnValueForMissingStub: null,
  );

  @override
  void goToSearch() => super.noSuchMethod(
    Invocation.method(#goToSearch, []),
    returnValueForMissingStub: null,
  );

  @override
  void goToDataManagement() => super.noSuchMethod(
    Invocation.method(#goToDataManagement, []),
    returnValueForMissingStub: null,
  );

  @override
  void resetSearchFocus() => super.noSuchMethod(
    Invocation.method(#resetSearchFocus, []),
    returnValueForMissingStub: null,
  );

  @override
  void goBack() => super.noSuchMethod(
    Invocation.method(#goBack, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SearchProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchProvider extends _i1.Mock implements _i16.SearchProvider {
  MockSearchProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.DatabaseService get databaseService =>
      (super.noSuchMethod(
            Invocation.getter(#databaseService),
            returnValue: _FakeDatabaseService_1(
              this,
              Invocation.getter(#databaseService),
            ),
          )
          as _i3.DatabaseService);

  @override
  _i4.OffApiService get offApiService =>
      (super.noSuchMethod(
            Invocation.getter(#offApiService),
            returnValue: _FakeOffApiService_2(
              this,
              Invocation.getter(#offApiService),
            ),
          )
          as _i4.OffApiService);

  @override
  _i5.SearchService get searchService =>
      (super.noSuchMethod(
            Invocation.getter(#searchService),
            returnValue: _FakeSearchService_3(
              this,
              Invocation.getter(#searchService),
            ),
          )
          as _i5.SearchService);

  @override
  List<_i13.Food> get searchResults =>
      (super.noSuchMethod(
            Invocation.getter(#searchResults),
            returnValue: <_i13.Food>[],
          )
          as List<_i13.Food>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  String get currentQuery =>
      (super.noSuchMethod(
            Invocation.getter(#currentQuery),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#currentQuery),
            ),
          )
          as String);

  @override
  _i18.SearchMode get searchMode =>
      (super.noSuchMethod(
            Invocation.getter(#searchMode),
            returnValue: _i18.SearchMode.text,
          )
          as _i18.SearchMode);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setSearchMode(_i18.SearchMode? mode) => super.noSuchMethod(
    Invocation.method(#setSearchMode, [mode]),
    returnValueForMissingStub: null,
  );

  @override
  void setSelectedCategoryId(int? id) => super.noSuchMethod(
    Invocation.method(#setSelectedCategoryId, [id]),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> textSearch(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#textSearch, [query]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> performOffSearch() =>
      (super.noSuchMethod(
            Invocation.method(#performOffSearch, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> barcodeSearch(String? barcode) =>
      (super.noSuchMethod(
            Invocation.method(#barcodeSearch, [barcode]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [GoalsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoalsProvider extends _i1.Mock implements _i19.GoalsProvider {
  MockGoalsProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.GoalSettings get settings =>
      (super.noSuchMethod(
            Invocation.getter(#settings),
            returnValue: _FakeGoalSettings_4(
              this,
              Invocation.getter(#settings),
            ),
          )
          as _i6.GoalSettings);

  @override
  _i7.MacroGoals get currentGoals =>
      (super.noSuchMethod(
            Invocation.getter(#currentGoals),
            returnValue: _FakeMacroGoals_5(
              this,
              Invocation.getter(#currentGoals),
            ),
          )
          as _i7.MacroGoals);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get showUpdateNotification =>
      (super.noSuchMethod(
            Invocation.getter(#showUpdateNotification),
            returnValue: false,
          )
          as bool);

  @override
  bool get isGoalsSet =>
      (super.noSuchMethod(Invocation.getter(#isGoalsSet), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void dismissNotification() => super.noSuchMethod(
    Invocation.method(#dismissNotification, []),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> saveSettings(_i6.GoalSettings? newSettings) =>
      (super.noSuchMethod(
            Invocation.method(#saveSettings, [newSettings]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> checkWeeklyUpdate() =>
      (super.noSuchMethod(
            Invocation.method(#checkWeeklyUpdate, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> recalculateTargets() =>
      (super.noSuchMethod(
            Invocation.method(#recalculateTargets, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
