// Mocks generated by Mockito 5.4.6 from annotations
// in free_cal_counter1/test/widgets/search_mode_tabs_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;
import 'dart:ui' as _i10;

import 'package:free_cal_counter1/models/food.dart' as _i6;
import 'package:free_cal_counter1/models/search_mode.dart' as _i8;
import 'package:free_cal_counter1/providers/search_provider.dart' as _i5;
import 'package:free_cal_counter1/services/database_service.dart' as _i2;
import 'package:free_cal_counter1/services/open_food_facts_service.dart' as _i3;
import 'package:free_cal_counter1/services/search_service.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabaseService_0 extends _i1.SmartFake
    implements _i2.DatabaseService {
  _FakeDatabaseService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOffApiService_1 extends _i1.SmartFake implements _i3.OffApiService {
  _FakeOffApiService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSearchService_2 extends _i1.SmartFake implements _i4.SearchService {
  _FakeSearchService_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SearchProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchProvider extends _i1.Mock implements _i5.SearchProvider {
  MockSearchProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseService get databaseService =>
      (super.noSuchMethod(
            Invocation.getter(#databaseService),
            returnValue: _FakeDatabaseService_0(
              this,
              Invocation.getter(#databaseService),
            ),
          )
          as _i2.DatabaseService);

  @override
  _i3.OffApiService get offApiService =>
      (super.noSuchMethod(
            Invocation.getter(#offApiService),
            returnValue: _FakeOffApiService_1(
              this,
              Invocation.getter(#offApiService),
            ),
          )
          as _i3.OffApiService);

  @override
  _i4.SearchService get searchService =>
      (super.noSuchMethod(
            Invocation.getter(#searchService),
            returnValue: _FakeSearchService_2(
              this,
              Invocation.getter(#searchService),
            ),
          )
          as _i4.SearchService);

  @override
  List<_i6.Food> get searchResults =>
      (super.noSuchMethod(
            Invocation.getter(#searchResults),
            returnValue: <_i6.Food>[],
          )
          as List<_i6.Food>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  String get currentQuery =>
      (super.noSuchMethod(
            Invocation.getter(#currentQuery),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#currentQuery),
            ),
          )
          as String);

  @override
  _i8.SearchMode get searchMode =>
      (super.noSuchMethod(
            Invocation.getter(#searchMode),
            returnValue: _i8.SearchMode.text,
          )
          as _i8.SearchMode);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setSearchMode(_i8.SearchMode? mode) => super.noSuchMethod(
    Invocation.method(#setSearchMode, [mode]),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<void> textSearch(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#textSearch, [query]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> performOffSearch() =>
      (super.noSuchMethod(
            Invocation.method(#performOffSearch, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> barcodeSearch(String? barcode) =>
      (super.noSuchMethod(
            Invocation.method(#barcodeSearch, [barcode]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
