// Mocks generated by Mockito 5.4.6 from annotations
// in free_cal_counter1/test/screens/data_management_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i5;

import 'package:free_cal_counter1/services/backup_config_service.dart' as _i7;
import 'package:free_cal_counter1/services/google_drive_service.dart' as _i3;
import 'package:google_sign_in/google_sign_in.dart' as _i2;
import 'package:googleapis/drive/v3.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGoogleSignInAuthentication_0 extends _i1.SmartFake
    implements _i2.GoogleSignInAuthentication {
  _FakeGoogleSignInAuthentication_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GoogleDriveService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleDriveService extends _i1.Mock
    implements _i3.GoogleDriveService {
  MockGoogleDriveService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.GoogleSignInAccount?> signIn() =>
      (super.noSuchMethod(
            Invocation.method(#signIn, []),
            returnValue: _i4.Future<_i2.GoogleSignInAccount?>.value(),
          )
          as _i4.Future<_i2.GoogleSignInAccount?>);

  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> isSignedIn() =>
      (super.noSuchMethod(
            Invocation.method(#isSignedIn, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i2.GoogleSignInAccount?> refreshCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#refreshCurrentUser, []),
            returnValue: _i4.Future<_i2.GoogleSignInAccount?>.value(),
          )
          as _i4.Future<_i2.GoogleSignInAccount?>);

  @override
  _i4.Future<void> silentSignIn() =>
      (super.noSuchMethod(
            Invocation.method(#silentSignIn, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> uploadBackup(_i5.File? file, {int? retentionCount = 7}) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadBackup,
              [file],
              {#retentionCount: retentionCount},
            ),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<List<_i6.File>> listBackups() =>
      (super.noSuchMethod(
            Invocation.method(#listBackups, []),
            returnValue: _i4.Future<List<_i6.File>>.value(<_i6.File>[]),
          )
          as _i4.Future<List<_i6.File>>);

  @override
  _i4.Future<_i5.File?> downloadBackup(String? fileId) =>
      (super.noSuchMethod(
            Invocation.method(#downloadBackup, [fileId]),
            returnValue: _i4.Future<_i5.File?>.value(),
          )
          as _i4.Future<_i5.File?>);
}

/// A class which mocks [BackupConfigService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackupConfigService extends _i1.Mock
    implements _i7.BackupConfigService {
  MockBackupConfigService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> setAutoBackupEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setAutoBackupEnabled, [enabled]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> isAutoBackupEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isAutoBackupEnabled, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> setRetentionCount(int? count) =>
      (super.noSuchMethod(
            Invocation.method(#setRetentionCount, [count]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> getRetentionCount() =>
      (super.noSuchMethod(
            Invocation.method(#getRetentionCount, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> markDirty() =>
      (super.noSuchMethod(
            Invocation.method(#markDirty, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearDirty() =>
      (super.noSuchMethod(
            Invocation.method(#clearDirty, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> isDirty() =>
      (super.noSuchMethod(
            Invocation.method(#isDirty, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> updateLastBackupTime() =>
      (super.noSuchMethod(
            Invocation.method(#updateLastBackupTime, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<DateTime?> getLastBackupTime() =>
      (super.noSuchMethod(
            Invocation.method(#getLastBackupTime, []),
            returnValue: _i4.Future<DateTime?>.value(),
          )
          as _i4.Future<DateTime?>);
}

/// A class which mocks [GoogleSignInAccount].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockGoogleSignInAccount extends _i1.Mock
    implements _i2.GoogleSignInAccount {
  MockGoogleSignInAccount() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get email =>
      (super.noSuchMethod(
            Invocation.getter(#email),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#email),
            ),
          )
          as String);

  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i8.dummyValue<String>(this, Invocation.getter(#id)),
          )
          as String);

  @override
  _i4.Future<_i2.GoogleSignInAuthentication> get authentication =>
      (super.noSuchMethod(
            Invocation.getter(#authentication),
            returnValue: _i4.Future<_i2.GoogleSignInAuthentication>.value(
              _FakeGoogleSignInAuthentication_0(
                this,
                Invocation.getter(#authentication),
              ),
            ),
          )
          as _i4.Future<_i2.GoogleSignInAuthentication>);

  @override
  _i4.Future<Map<String, String>> get authHeaders =>
      (super.noSuchMethod(
            Invocation.getter(#authHeaders),
            returnValue: _i4.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i4.Future<Map<String, String>>);

  @override
  _i4.Future<void> clearAuthCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearAuthCache, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
