// Mocks generated by Mockito 5.4.6 from annotations
// in free_cal_counter1/test/screens/ingredient_edit_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i8;

import 'package:free_cal_counter1/models/category.dart' as _i5;
import 'package:free_cal_counter1/models/recipe.dart' as _i7;
import 'package:free_cal_counter1/models/recipe_item.dart' as _i4;
import 'package:free_cal_counter1/providers/recipe_provider.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [RecipeProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecipeProvider extends _i1.Mock implements _i2.RecipeProvider {
  MockRecipeProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i3.dummyValue<String>(this, Invocation.getter(#name)),
          )
          as String);

  @override
  double get servingsCreated =>
      (super.noSuchMethod(Invocation.getter(#servingsCreated), returnValue: 0.0)
          as double);

  @override
  String get portionName =>
      (super.noSuchMethod(
            Invocation.getter(#portionName),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#portionName),
            ),
          )
          as String);

  @override
  String get notes =>
      (super.noSuchMethod(
            Invocation.getter(#notes),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#notes),
            ),
          )
          as String);

  @override
  bool get isTemplate =>
      (super.noSuchMethod(Invocation.getter(#isTemplate), returnValue: false)
          as bool);

  @override
  List<_i4.RecipeItem> get items =>
      (super.noSuchMethod(
            Invocation.getter(#items),
            returnValue: <_i4.RecipeItem>[],
          )
          as List<_i4.RecipeItem>);

  @override
  List<_i5.Category> get selectedCategories =>
      (super.noSuchMethod(
            Invocation.getter(#selectedCategories),
            returnValue: <_i5.Category>[],
          )
          as List<_i5.Category>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  double get totalCalories =>
      (super.noSuchMethod(Invocation.getter(#totalCalories), returnValue: 0.0)
          as double);

  @override
  double get totalProtein =>
      (super.noSuchMethod(Invocation.getter(#totalProtein), returnValue: 0.0)
          as double);

  @override
  double get totalFat =>
      (super.noSuchMethod(Invocation.getter(#totalFat), returnValue: 0.0)
          as double);

  @override
  double get totalCarbs =>
      (super.noSuchMethod(Invocation.getter(#totalCarbs), returnValue: 0.0)
          as double);

  @override
  double get totalFiber =>
      (super.noSuchMethod(Invocation.getter(#totalFiber), returnValue: 0.0)
          as double);

  @override
  double get caloriesPerPortion =>
      (super.noSuchMethod(
            Invocation.getter(#caloriesPerPortion),
            returnValue: 0.0,
          )
          as double);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setName(String? val) => super.noSuchMethod(
    Invocation.method(#setName, [val]),
    returnValueForMissingStub: null,
  );

  @override
  void setServingsCreated(double? val) => super.noSuchMethod(
    Invocation.method(#setServingsCreated, [val]),
    returnValueForMissingStub: null,
  );

  @override
  void setFinalWeightGrams(double? val) => super.noSuchMethod(
    Invocation.method(#setFinalWeightGrams, [val]),
    returnValueForMissingStub: null,
  );

  @override
  void setPortionName(String? val) => super.noSuchMethod(
    Invocation.method(#setPortionName, [val]),
    returnValueForMissingStub: null,
  );

  @override
  void setNotes(String? val) => super.noSuchMethod(
    Invocation.method(#setNotes, [val]),
    returnValueForMissingStub: null,
  );

  @override
  void setIsTemplate(bool? val) => super.noSuchMethod(
    Invocation.method(#setIsTemplate, [val]),
    returnValueForMissingStub: null,
  );

  @override
  void addItem(_i4.RecipeItem? item) => super.noSuchMethod(
    Invocation.method(#addItem, [item]),
    returnValueForMissingStub: null,
  );

  @override
  void removeItem(int? index) => super.noSuchMethod(
    Invocation.method(#removeItem, [index]),
    returnValueForMissingStub: null,
  );

  @override
  void updateItem(int? index, _i4.RecipeItem? newItem) => super.noSuchMethod(
    Invocation.method(#updateItem, [index, newItem]),
    returnValueForMissingStub: null,
  );

  @override
  void toggleCategory(_i5.Category? category) => super.noSuchMethod(
    Invocation.method(#toggleCategory, [category]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<bool> saveRecipe() =>
      (super.noSuchMethod(
            Invocation.method(#saveRecipe, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  void reset() => super.noSuchMethod(
    Invocation.method(#reset, []),
    returnValueForMissingStub: null,
  );

  @override
  void loadFromRecipe(_i7.Recipe? recipe) => super.noSuchMethod(
    Invocation.method(#loadFromRecipe, [recipe]),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
