// Mocks generated by Mockito 5.4.6 from annotations
// in free_cal_counter1/test/screens/log_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:ui' as _i11;

import 'package:free_cal_counter1/models/daily_macro_stats.dart' as _i2;
import 'package:free_cal_counter1/models/food.dart' as _i6;
import 'package:free_cal_counter1/models/food_portion.dart' as _i8;
import 'package:free_cal_counter1/models/food_serving.dart' as _i15;
import 'package:free_cal_counter1/models/logged_food.dart' as _i9;
import 'package:free_cal_counter1/models/search_mode.dart' as _i14;
import 'package:free_cal_counter1/providers/food_search_provider.dart' as _i13;
import 'package:free_cal_counter1/providers/log_provider.dart' as _i7;
import 'package:free_cal_counter1/providers/navigation_provider.dart' as _i12;
import 'package:free_cal_counter1/services/database_service.dart' as _i3;
import 'package:free_cal_counter1/services/food_search_service.dart' as _i5;
import 'package:free_cal_counter1/services/open_food_facts_service.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDailyMacroStats_0 extends _i1.SmartFake
    implements _i2.DailyMacroStats {
  _FakeDailyMacroStats_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseService_1 extends _i1.SmartFake
    implements _i3.DatabaseService {
  _FakeDatabaseService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOffApiService_2 extends _i1.SmartFake implements _i4.OffApiService {
  _FakeOffApiService_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFoodSearchService_3 extends _i1.SmartFake
    implements _i5.FoodSearchService {
  _FakeFoodSearchService_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFood_4 extends _i1.SmartFake implements _i6.Food {
  _FakeFood_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LogProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogProvider extends _i1.Mock implements _i7.LogProvider {
  MockLogProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  double get loggedCalories =>
      (super.noSuchMethod(Invocation.getter(#loggedCalories), returnValue: 0.0)
          as double);

  @override
  double get queuedCalories =>
      (super.noSuchMethod(Invocation.getter(#queuedCalories), returnValue: 0.0)
          as double);

  @override
  double get queuedProtein =>
      (super.noSuchMethod(Invocation.getter(#queuedProtein), returnValue: 0.0)
          as double);

  @override
  double get queuedFat =>
      (super.noSuchMethod(Invocation.getter(#queuedFat), returnValue: 0.0)
          as double);

  @override
  double get queuedCarbs =>
      (super.noSuchMethod(Invocation.getter(#queuedCarbs), returnValue: 0.0)
          as double);

  @override
  double get queuedFiber =>
      (super.noSuchMethod(Invocation.getter(#queuedFiber), returnValue: 0.0)
          as double);

  @override
  double get totalCalories =>
      (super.noSuchMethod(Invocation.getter(#totalCalories), returnValue: 0.0)
          as double);

  @override
  double get totalProtein =>
      (super.noSuchMethod(Invocation.getter(#totalProtein), returnValue: 0.0)
          as double);

  @override
  double get totalFat =>
      (super.noSuchMethod(Invocation.getter(#totalFat), returnValue: 0.0)
          as double);

  @override
  double get totalCarbs =>
      (super.noSuchMethod(Invocation.getter(#totalCarbs), returnValue: 0.0)
          as double);

  @override
  double get totalFiber =>
      (super.noSuchMethod(Invocation.getter(#totalFiber), returnValue: 0.0)
          as double);

  @override
  double get dailyTargetCalories =>
      (super.noSuchMethod(
            Invocation.getter(#dailyTargetCalories),
            returnValue: 0.0,
          )
          as double);

  @override
  double get dailyTargetProtein =>
      (super.noSuchMethod(
            Invocation.getter(#dailyTargetProtein),
            returnValue: 0.0,
          )
          as double);

  @override
  double get dailyTargetFat =>
      (super.noSuchMethod(Invocation.getter(#dailyTargetFat), returnValue: 0.0)
          as double);

  @override
  double get dailyTargetCarbs =>
      (super.noSuchMethod(
            Invocation.getter(#dailyTargetCarbs),
            returnValue: 0.0,
          )
          as double);

  @override
  double get dailyTargetFiber =>
      (super.noSuchMethod(
            Invocation.getter(#dailyTargetFiber),
            returnValue: 0.0,
          )
          as double);

  @override
  List<_i8.FoodPortion> get logQueue =>
      (super.noSuchMethod(
            Invocation.getter(#logQueue),
            returnValue: <_i8.FoodPortion>[],
          )
          as List<_i8.FoodPortion>);

  @override
  List<_i9.LoggedFood> get loggedFoods =>
      (super.noSuchMethod(
            Invocation.getter(#loggedFoods),
            returnValue: <_i9.LoggedFood>[],
          )
          as List<_i9.LoggedFood>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void addFoodToQueue(_i8.FoodPortion? serving) => super.noSuchMethod(
    Invocation.method(#addFoodToQueue, [serving]),
    returnValueForMissingStub: null,
  );

  @override
  void updateFoodInQueue(int? index, _i8.FoodPortion? newPortion) =>
      super.noSuchMethod(
        Invocation.method(#updateFoodInQueue, [index, newPortion]),
        returnValueForMissingStub: null,
      );

  @override
  void removeFoodFromQueue(_i8.FoodPortion? serving) => super.noSuchMethod(
    Invocation.method(#removeFoodFromQueue, [serving]),
    returnValueForMissingStub: null,
  );

  @override
  void clearQueue() => super.noSuchMethod(
    Invocation.method(#clearQueue, []),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> logQueueToDatabase() =>
      (super.noSuchMethod(
            Invocation.method(#logQueueToDatabase, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> loadLoggedFoodsForDate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#loadLoggedFoodsForDate, [date]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> deleteLoggedFood(_i9.LoggedFood? food) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLoggedFood, [food]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<_i2.DailyMacroStats>> getDailyMacroStats(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDailyMacroStats, [start, end]),
            returnValue: _i10.Future<List<_i2.DailyMacroStats>>.value(
              <_i2.DailyMacroStats>[],
            ),
          )
          as _i10.Future<List<_i2.DailyMacroStats>>);

  @override
  _i10.Future<_i2.DailyMacroStats> getTodayStats() =>
      (super.noSuchMethod(
            Invocation.method(#getTodayStats, []),
            returnValue: _i10.Future<_i2.DailyMacroStats>.value(
              _FakeDailyMacroStats_0(
                this,
                Invocation.method(#getTodayStats, []),
              ),
            ),
          )
          as _i10.Future<_i2.DailyMacroStats>);

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NavigationProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationProvider extends _i1.Mock
    implements _i12.NavigationProvider {
  MockNavigationProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get selectedIndex =>
      (super.noSuchMethod(Invocation.getter(#selectedIndex), returnValue: 0)
          as int);

  @override
  bool get shouldFocusSearch =>
      (super.noSuchMethod(
            Invocation.getter(#shouldFocusSearch),
            returnValue: false,
          )
          as bool);

  @override
  bool get showConsumed =>
      (super.noSuchMethod(Invocation.getter(#showConsumed), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setShowConsumed(bool? value) => super.noSuchMethod(
    Invocation.method(#setShowConsumed, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void changeTab(int? index) => super.noSuchMethod(
    Invocation.method(#changeTab, [index]),
    returnValueForMissingStub: null,
  );

  @override
  void goToFoodSearch() => super.noSuchMethod(
    Invocation.method(#goToFoodSearch, []),
    returnValueForMissingStub: null,
  );

  @override
  void resetSearchFocus() => super.noSuchMethod(
    Invocation.method(#resetSearchFocus, []),
    returnValueForMissingStub: null,
  );

  @override
  void goBack() => super.noSuchMethod(
    Invocation.method(#goBack, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [FoodSearchProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockFoodSearchProvider extends _i1.Mock
    implements _i13.FoodSearchProvider {
  MockFoodSearchProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.DatabaseService get databaseService =>
      (super.noSuchMethod(
            Invocation.getter(#databaseService),
            returnValue: _FakeDatabaseService_1(
              this,
              Invocation.getter(#databaseService),
            ),
          )
          as _i3.DatabaseService);

  @override
  _i4.OffApiService get offApiService =>
      (super.noSuchMethod(
            Invocation.getter(#offApiService),
            returnValue: _FakeOffApiService_2(
              this,
              Invocation.getter(#offApiService),
            ),
          )
          as _i4.OffApiService);

  @override
  _i5.FoodSearchService get foodSearchService =>
      (super.noSuchMethod(
            Invocation.getter(#foodSearchService),
            returnValue: _FakeFoodSearchService_3(
              this,
              Invocation.getter(#foodSearchService),
            ),
          )
          as _i5.FoodSearchService);

  @override
  List<_i6.Food> get searchResults =>
      (super.noSuchMethod(
            Invocation.getter(#searchResults),
            returnValue: <_i6.Food>[],
          )
          as List<_i6.Food>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  _i14.SearchMode get searchMode =>
      (super.noSuchMethod(
            Invocation.getter(#searchMode),
            returnValue: _i14.SearchMode.text,
          )
          as _i14.SearchMode);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setSearchMode(_i14.SearchMode? mode) => super.noSuchMethod(
    Invocation.method(#setSearchMode, [mode]),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> textSearch(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#textSearch, [query]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> performOffSearch() =>
      (super.noSuchMethod(
            Invocation.method(#performOffSearch, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> barcodeSearch(String? barcode) =>
      (super.noSuchMethod(
            Invocation.method(#barcodeSearch, [barcode]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i3.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<_i6.Food>> searchFoodsByName(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchFoodsByName, [query]),
            returnValue: _i10.Future<List<_i6.Food>>.value(<_i6.Food>[]),
          )
          as _i10.Future<List<_i6.Food>>);

  @override
  _i10.Future<List<_i15.FoodServing>> getServingsForFood(
    int? foodId,
    String? foodSource,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getServingsForFood, [foodId, foodSource]),
            returnValue: _i10.Future<List<_i15.FoodServing>>.value(
              <_i15.FoodServing>[],
            ),
          )
          as _i10.Future<List<_i15.FoodServing>>);

  @override
  _i10.Future<String?> getLastLoggedUnit(int? originalFoodId) =>
      (super.noSuchMethod(
            Invocation.method(#getLastLoggedUnit, [originalFoodId]),
            returnValue: _i10.Future<String?>.value(),
          )
          as _i10.Future<String?>);

  @override
  _i10.Future<_i6.Food?> getFoodByBarcode(String? barcode) =>
      (super.noSuchMethod(
            Invocation.method(#getFoodByBarcode, [barcode]),
            returnValue: _i10.Future<_i6.Food?>.value(),
          )
          as _i10.Future<_i6.Food?>);

  @override
  _i10.Future<_i6.Food?> getFoodBySourceFdcId(int? fdcId) =>
      (super.noSuchMethod(
            Invocation.method(#getFoodBySourceFdcId, [fdcId]),
            returnValue: _i10.Future<_i6.Food?>.value(),
          )
          as _i10.Future<_i6.Food?>);

  @override
  _i10.Future<void> logPortions(
    List<_i8.FoodPortion>? portions,
    DateTime? logTimestamp,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#logPortions, [portions, logTimestamp]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<_i9.LoggedFood>> getLoggedPortionsForDate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#getLoggedPortionsForDate, [date]),
            returnValue: _i10.Future<List<_i9.LoggedFood>>.value(
              <_i9.LoggedFood>[],
            ),
          )
          as _i10.Future<List<_i9.LoggedFood>>);

  @override
  _i10.Future<_i6.Food> saveFood(_i6.Food? food) =>
      (super.noSuchMethod(
            Invocation.method(#saveFood, [food]),
            returnValue: _i10.Future<_i6.Food>.value(
              _FakeFood_4(this, Invocation.method(#saveFood, [food])),
            ),
          )
          as _i10.Future<_i6.Food>);

  @override
  _i10.Future<void> deleteLoggedPortion(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLoggedPortion, [id]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<List<_i2.LoggedMacroDTO>> getLoggedMacrosForDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLoggedMacrosForDateRange, [start, end]),
            returnValue: _i10.Future<List<_i2.LoggedMacroDTO>>.value(
              <_i2.LoggedMacroDTO>[],
            ),
          )
          as _i10.Future<List<_i2.LoggedMacroDTO>>);
}
