// Mocks generated by Mockito 5.4.6 from annotations
// in free_cal_counter1/test/screens/log_queue_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i4;

import 'package:free_cal_counter1/models/food.dart' as _i3;
import 'package:free_cal_counter1/providers/log_provider.dart' as _i2;
import 'package:free_cal_counter1/providers/navigation_provider.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LogProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogProvider extends _i1.Mock implements _i2.LogProvider {
  MockLogProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  double get loggedCalories =>
      (super.noSuchMethod(Invocation.getter(#loggedCalories), returnValue: 0.0)
          as double);

  @override
  double get queuedCalories =>
      (super.noSuchMethod(Invocation.getter(#queuedCalories), returnValue: 0.0)
          as double);

  @override
  double get totalCalories =>
      (super.noSuchMethod(Invocation.getter(#totalCalories), returnValue: 0.0)
          as double);

  @override
  double get dailyTargetCalories =>
      (super.noSuchMethod(
            Invocation.getter(#dailyTargetCalories),
            returnValue: 0.0,
          )
          as double);

  @override
  List<_i3.Food> get logQueue =>
      (super.noSuchMethod(
            Invocation.getter(#logQueue),
            returnValue: <_i3.Food>[],
          )
          as List<_i3.Food>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void updateLoggedCalories(double? calories) => super.noSuchMethod(
    Invocation.method(#updateLoggedCalories, [calories]),
    returnValueForMissingStub: null,
  );

  @override
  void updateQueuedCalories(double? calories) => super.noSuchMethod(
    Invocation.method(#updateQueuedCalories, [calories]),
    returnValueForMissingStub: null,
  );

  @override
  void updateDailyTargetCalories(double? target) => super.noSuchMethod(
    Invocation.method(#updateDailyTargetCalories, [target]),
    returnValueForMissingStub: null,
  );

  @override
  void addFoodToQueue(_i3.Food? food) => super.noSuchMethod(
    Invocation.method(#addFoodToQueue, [food]),
    returnValueForMissingStub: null,
  );

  @override
  void removeFoodFromQueue(_i3.Food? food) => super.noSuchMethod(
    Invocation.method(#removeFoodFromQueue, [food]),
    returnValueForMissingStub: null,
  );

  @override
  void clearQueue() => super.noSuchMethod(
    Invocation.method(#clearQueue, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NavigationProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationProvider extends _i1.Mock
    implements _i5.NavigationProvider {
  MockNavigationProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get selectedIndex =>
      (super.noSuchMethod(Invocation.getter(#selectedIndex), returnValue: 0)
          as int);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void changeTab(int? index) => super.noSuchMethod(
    Invocation.method(#changeTab, [index]),
    returnValueForMissingStub: null,
  );

  @override
  void goToFoodSearch() => super.noSuchMethod(
    Invocation.method(#goToFoodSearch, []),
    returnValueForMissingStub: null,
  );

  @override
  void goBack() => super.noSuchMethod(
    Invocation.method(#goBack, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
