// Mocks generated by Mockito 5.4.6 from annotations
// in free_cal_counter1/test/screens/log_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i13;
import 'dart:io' as _i19;
import 'dart:ui' as _i14;

import 'package:free_cal_counter1/models/category.dart' as _i23;
import 'package:free_cal_counter1/models/daily_macro_stats.dart' as _i2;
import 'package:free_cal_counter1/models/food.dart' as _i7;
import 'package:free_cal_counter1/models/food_container.dart' as _i22;
import 'package:free_cal_counter1/models/food_portion.dart' as _i11;
import 'package:free_cal_counter1/models/food_serving.dart' as _i20;
import 'package:free_cal_counter1/models/food_usage_stats.dart' as _i24;
import 'package:free_cal_counter1/models/goal_settings.dart' as _i8;
import 'package:free_cal_counter1/models/logged_portion.dart' as _i12;
import 'package:free_cal_counter1/models/macro_goals.dart' as _i9;
import 'package:free_cal_counter1/models/recipe.dart' as _i6;
import 'package:free_cal_counter1/models/search_mode.dart' as _i18;
import 'package:free_cal_counter1/models/weight.dart' as _i21;
import 'package:free_cal_counter1/providers/goals_provider.dart' as _i25;
import 'package:free_cal_counter1/providers/log_provider.dart' as _i10;
import 'package:free_cal_counter1/providers/navigation_provider.dart' as _i15;
import 'package:free_cal_counter1/providers/search_provider.dart' as _i16;
import 'package:free_cal_counter1/providers/weight_provider.dart' as _i26;
import 'package:free_cal_counter1/services/database_service.dart' as _i3;
import 'package:free_cal_counter1/services/open_food_facts_service.dart' as _i4;
import 'package:free_cal_counter1/services/search_service.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i17;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDailyMacroStats_0 extends _i1.SmartFake
    implements _i2.DailyMacroStats {
  _FakeDailyMacroStats_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseService_1 extends _i1.SmartFake
    implements _i3.DatabaseService {
  _FakeDatabaseService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOffApiService_2 extends _i1.SmartFake implements _i4.OffApiService {
  _FakeOffApiService_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSearchService_3 extends _i1.SmartFake implements _i5.SearchService {
  _FakeSearchService_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRecipe_4 extends _i1.SmartFake implements _i6.Recipe {
  _FakeRecipe_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFood_5 extends _i1.SmartFake implements _i7.Food {
  _FakeFood_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoalSettings_6 extends _i1.SmartFake implements _i8.GoalSettings {
  _FakeGoalSettings_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMacroGoals_7 extends _i1.SmartFake implements _i9.MacroGoals {
  _FakeMacroGoals_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LogProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogProvider extends _i1.Mock implements _i10.LogProvider {
  MockLogProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  double get loggedCalories =>
      (super.noSuchMethod(Invocation.getter(#loggedCalories), returnValue: 0.0)
          as double);

  @override
  double get queuedCalories =>
      (super.noSuchMethod(Invocation.getter(#queuedCalories), returnValue: 0.0)
          as double);

  @override
  double get queuedProtein =>
      (super.noSuchMethod(Invocation.getter(#queuedProtein), returnValue: 0.0)
          as double);

  @override
  double get queuedFat =>
      (super.noSuchMethod(Invocation.getter(#queuedFat), returnValue: 0.0)
          as double);

  @override
  double get queuedCarbs =>
      (super.noSuchMethod(Invocation.getter(#queuedCarbs), returnValue: 0.0)
          as double);

  @override
  double get queuedFiber =>
      (super.noSuchMethod(Invocation.getter(#queuedFiber), returnValue: 0.0)
          as double);

  @override
  double get totalCalories =>
      (super.noSuchMethod(Invocation.getter(#totalCalories), returnValue: 0.0)
          as double);

  @override
  double get totalProtein =>
      (super.noSuchMethod(Invocation.getter(#totalProtein), returnValue: 0.0)
          as double);

  @override
  double get totalFat =>
      (super.noSuchMethod(Invocation.getter(#totalFat), returnValue: 0.0)
          as double);

  @override
  double get totalCarbs =>
      (super.noSuchMethod(Invocation.getter(#totalCarbs), returnValue: 0.0)
          as double);

  @override
  double get totalFiber =>
      (super.noSuchMethod(Invocation.getter(#totalFiber), returnValue: 0.0)
          as double);

  @override
  double get dailyTargetCalories =>
      (super.noSuchMethod(
            Invocation.getter(#dailyTargetCalories),
            returnValue: 0.0,
          )
          as double);

  @override
  double get dailyTargetProtein =>
      (super.noSuchMethod(
            Invocation.getter(#dailyTargetProtein),
            returnValue: 0.0,
          )
          as double);

  @override
  double get dailyTargetFat =>
      (super.noSuchMethod(Invocation.getter(#dailyTargetFat), returnValue: 0.0)
          as double);

  @override
  double get dailyTargetCarbs =>
      (super.noSuchMethod(
            Invocation.getter(#dailyTargetCarbs),
            returnValue: 0.0,
          )
          as double);

  @override
  double get dailyTargetFiber =>
      (super.noSuchMethod(
            Invocation.getter(#dailyTargetFiber),
            returnValue: 0.0,
          )
          as double);

  @override
  List<_i11.FoodPortion> get logQueue =>
      (super.noSuchMethod(
            Invocation.getter(#logQueue),
            returnValue: <_i11.FoodPortion>[],
          )
          as List<_i11.FoodPortion>);

  @override
  List<_i12.LoggedPortion> get loggedPortion =>
      (super.noSuchMethod(
            Invocation.getter(#loggedPortion),
            returnValue: <_i12.LoggedPortion>[],
          )
          as List<_i12.LoggedPortion>);

  @override
  bool get isFasted =>
      (super.noSuchMethod(Invocation.getter(#isFasted), returnValue: false)
          as bool);

  @override
  Set<int> get selectedPortionIds =>
      (super.noSuchMethod(
            Invocation.getter(#selectedPortionIds),
            returnValue: <int>{},
          )
          as Set<int>);

  @override
  bool get hasSelectedPortions =>
      (super.noSuchMethod(
            Invocation.getter(#hasSelectedPortions),
            returnValue: false,
          )
          as bool);

  @override
  int get selectedPortionCount =>
      (super.noSuchMethod(
            Invocation.getter(#selectedPortionCount),
            returnValue: 0,
          )
          as int);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void addFoodToQueue(_i11.FoodPortion? serving) => super.noSuchMethod(
    Invocation.method(#addFoodToQueue, [serving]),
    returnValueForMissingStub: null,
  );

  @override
  void addRecipeToQueue(_i6.Recipe? recipe, {double? quantity = 1.0}) =>
      super.noSuchMethod(
        Invocation.method(#addRecipeToQueue, [recipe], {#quantity: quantity}),
        returnValueForMissingStub: null,
      );

  @override
  void dumpRecipeToQueue(_i6.Recipe? recipe, {double? quantity = 1.0}) =>
      super.noSuchMethod(
        Invocation.method(#dumpRecipeToQueue, [recipe], {#quantity: quantity}),
        returnValueForMissingStub: null,
      );

  @override
  void updateFoodInQueue(int? index, _i11.FoodPortion? newPortion) =>
      super.noSuchMethod(
        Invocation.method(#updateFoodInQueue, [index, newPortion]),
        returnValueForMissingStub: null,
      );

  @override
  void removeFoodFromQueue(_i11.FoodPortion? serving) => super.noSuchMethod(
    Invocation.method(#removeFoodFromQueue, [serving]),
    returnValueForMissingStub: null,
  );

  @override
  void clearQueue() => super.noSuchMethod(
    Invocation.method(#clearQueue, []),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Future<void> refreshFoodInQueue(int? foodId, _i7.Food? updatedFood) =>
      (super.noSuchMethod(
            Invocation.method(#refreshFoodInQueue, [foodId, updatedFood]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> logQueueToDatabase() =>
      (super.noSuchMethod(
            Invocation.method(#logQueueToDatabase, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> loadLoggedPortionsForDate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#loadLoggedPortionsForDate, [date]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> toggleFasted(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFasted, [date]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> deleteLoggedPortion(_i12.LoggedPortion? food) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLoggedPortion, [food]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> updateLoggedPortion(
    _i12.LoggedPortion? oldLoggedPortion,
    _i11.FoodPortion? newPortion,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateLoggedPortion, [
              oldLoggedPortion,
              newPortion,
            ]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<List<_i2.DailyMacroStats>> getDailyMacroStats(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDailyMacroStats, [start, end]),
            returnValue: _i13.Future<List<_i2.DailyMacroStats>>.value(
              <_i2.DailyMacroStats>[],
            ),
          )
          as _i13.Future<List<_i2.DailyMacroStats>>);

  @override
  _i13.Future<_i2.DailyMacroStats> getTodayStats() =>
      (super.noSuchMethod(
            Invocation.method(#getTodayStats, []),
            returnValue: _i13.Future<_i2.DailyMacroStats>.value(
              _FakeDailyMacroStats_0(
                this,
                Invocation.method(#getTodayStats, []),
              ),
            ),
          )
          as _i13.Future<_i2.DailyMacroStats>);

  @override
  void togglePortionSelection(int? portionId) => super.noSuchMethod(
    Invocation.method(#togglePortionSelection, [portionId]),
    returnValueForMissingStub: null,
  );

  @override
  void selectPortion(int? portionId) => super.noSuchMethod(
    Invocation.method(#selectPortion, [portionId]),
    returnValueForMissingStub: null,
  );

  @override
  void deselectPortion(int? portionId) => super.noSuchMethod(
    Invocation.method(#deselectPortion, [portionId]),
    returnValueForMissingStub: null,
  );

  @override
  void clearSelection() => super.noSuchMethod(
    Invocation.method(#clearSelection, []),
    returnValueForMissingStub: null,
  );

  @override
  bool isPortionSelected(int? portionId) =>
      (super.noSuchMethod(
            Invocation.method(#isPortionSelected, [portionId]),
            returnValue: false,
          )
          as bool);

  @override
  void copySelectedPortionsToQueue() => super.noSuchMethod(
    Invocation.method(#copySelectedPortionsToQueue, []),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Future<void> moveSelectedPortions(DateTime? newTimestamp) =>
      (super.noSuchMethod(
            Invocation.method(#moveSelectedPortions, [newTimestamp]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> deleteSelectedPortions() =>
      (super.noSuchMethod(
            Invocation.method(#deleteSelectedPortions, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NavigationProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationProvider extends _i1.Mock
    implements _i15.NavigationProvider {
  MockNavigationProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get selectedIndex =>
      (super.noSuchMethod(Invocation.getter(#selectedIndex), returnValue: 0)
          as int);

  @override
  bool get shouldFocusSearch =>
      (super.noSuchMethod(
            Invocation.getter(#shouldFocusSearch),
            returnValue: false,
          )
          as bool);

  @override
  bool get showConsumed =>
      (super.noSuchMethod(Invocation.getter(#showConsumed), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setShowConsumed(bool? value) => super.noSuchMethod(
    Invocation.method(#setShowConsumed, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void changeTab(int? index) => super.noSuchMethod(
    Invocation.method(#changeTab, [index]),
    returnValueForMissingStub: null,
  );

  @override
  void goToSearch() => super.noSuchMethod(
    Invocation.method(#goToSearch, []),
    returnValueForMissingStub: null,
  );

  @override
  void goToDataManagement() => super.noSuchMethod(
    Invocation.method(#goToDataManagement, []),
    returnValueForMissingStub: null,
  );

  @override
  void resetSearchFocus() => super.noSuchMethod(
    Invocation.method(#resetSearchFocus, []),
    returnValueForMissingStub: null,
  );

  @override
  void goBack() => super.noSuchMethod(
    Invocation.method(#goBack, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SearchProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchProvider extends _i1.Mock implements _i16.SearchProvider {
  MockSearchProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.DatabaseService get databaseService =>
      (super.noSuchMethod(
            Invocation.getter(#databaseService),
            returnValue: _FakeDatabaseService_1(
              this,
              Invocation.getter(#databaseService),
            ),
          )
          as _i3.DatabaseService);

  @override
  _i4.OffApiService get offApiService =>
      (super.noSuchMethod(
            Invocation.getter(#offApiService),
            returnValue: _FakeOffApiService_2(
              this,
              Invocation.getter(#offApiService),
            ),
          )
          as _i4.OffApiService);

  @override
  _i5.SearchService get searchService =>
      (super.noSuchMethod(
            Invocation.getter(#searchService),
            returnValue: _FakeSearchService_3(
              this,
              Invocation.getter(#searchService),
            ),
          )
          as _i5.SearchService);

  @override
  List<_i7.Food> get searchResults =>
      (super.noSuchMethod(
            Invocation.getter(#searchResults),
            returnValue: <_i7.Food>[],
          )
          as List<_i7.Food>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  String get currentQuery =>
      (super.noSuchMethod(
            Invocation.getter(#currentQuery),
            returnValue: _i17.dummyValue<String>(
              this,
              Invocation.getter(#currentQuery),
            ),
          )
          as String);

  @override
  _i18.SearchMode get searchMode =>
      (super.noSuchMethod(
            Invocation.getter(#searchMode),
            returnValue: _i18.SearchMode.text,
          )
          as _i18.SearchMode);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setSearchMode(_i18.SearchMode? mode) => super.noSuchMethod(
    Invocation.method(#setSearchMode, [mode]),
    returnValueForMissingStub: null,
  );

  @override
  void setSelectedCategoryId(int? id) => super.noSuchMethod(
    Invocation.method(#setSelectedCategoryId, [id]),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Future<void> textSearch(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#textSearch, [query]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> performOffSearch() =>
      (super.noSuchMethod(
            Invocation.method(#performOffSearch, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> barcodeSearch(String? barcode) =>
      (super.noSuchMethod(
            Invocation.method(#barcodeSearch, [barcode]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i3.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> restoreDatabase(_i19.File? backupFile) =>
      (super.noSuchMethod(
            Invocation.method(#restoreDatabase, [backupFile]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<List<_i7.Food>> searchFoodsByName(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchFoodsByName, [query]),
            returnValue: _i13.Future<List<_i7.Food>>.value(<_i7.Food>[]),
          )
          as _i13.Future<List<_i7.Food>>);

  @override
  _i13.Future<List<_i20.FoodServing>> getServingsForFood(
    int? foodId,
    String? foodSource,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getServingsForFood, [foodId, foodSource]),
            returnValue: _i13.Future<List<_i20.FoodServing>>.value(
              <_i20.FoodServing>[],
            ),
          )
          as _i13.Future<List<_i20.FoodServing>>);

  @override
  _i13.Future<Map<int, List<_i20.FoodServing>>> getServingsForFoods(
    List<int>? foodIds,
    String? foodSource,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getServingsForFoods, [foodIds, foodSource]),
            returnValue: _i13.Future<Map<int, List<_i20.FoodServing>>>.value(
              <int, List<_i20.FoodServing>>{},
            ),
          )
          as _i13.Future<Map<int, List<_i20.FoodServing>>>);

  @override
  _i13.Future<String?> getLastLoggedUnit(int? originalFoodId) =>
      (super.noSuchMethod(
            Invocation.method(#getLastLoggedUnit, [originalFoodId]),
            returnValue: _i13.Future<String?>.value(),
          )
          as _i13.Future<String?>);

  @override
  _i13.Future<_i7.Food?> getFoodByBarcode(String? barcode) =>
      (super.noSuchMethod(
            Invocation.method(#getFoodByBarcode, [barcode]),
            returnValue: _i13.Future<_i7.Food?>.value(),
          )
          as _i13.Future<_i7.Food?>);

  @override
  _i13.Future<_i7.Food?> getFoodBySourceFdcId(int? fdcId) =>
      (super.noSuchMethod(
            Invocation.method(#getFoodBySourceFdcId, [fdcId]),
            returnValue: _i13.Future<_i7.Food?>.value(),
          )
          as _i13.Future<_i7.Food?>);

  @override
  _i13.Future<void> logPortions(
    List<_i11.FoodPortion>? portions,
    DateTime? logTimestamp,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#logPortions, [portions, logTimestamp]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<bool> isRecipeLogged(int? recipeId) =>
      (super.noSuchMethod(
            Invocation.method(#isRecipeLogged, [recipeId]),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  _i13.Future<bool> isRecipeUsedAsIngredient(int? recipeId) =>
      (super.noSuchMethod(
            Invocation.method(#isRecipeUsedAsIngredient, [recipeId]),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  _i13.Future<void> hideRecipe(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#hideRecipe, [id]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<List<_i12.LoggedPortion>> getLoggedPortionsForDate(
    DateTime? date,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLoggedPortionsForDate, [date]),
            returnValue: _i13.Future<List<_i12.LoggedPortion>>.value(
              <_i12.LoggedPortion>[],
            ),
          )
          as _i13.Future<List<_i12.LoggedPortion>>);

  @override
  _i13.Future<int> saveFood(_i7.Food? food) =>
      (super.noSuchMethod(
            Invocation.method(#saveFood, [food]),
            returnValue: _i13.Future<int>.value(0),
          )
          as _i13.Future<int>);

  @override
  _i13.Future<void> deleteLoggedPortion(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLoggedPortion, [id]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> deleteLoggedPortions(List<int>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLoggedPortions, [ids]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> updateLoggedPortion(
    int? loggedPortionId,
    _i11.FoodPortion? newPortion,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateLoggedPortion, [
              loggedPortionId,
              newPortion,
            ]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> saveWeight(_i21.Weight? weight) =>
      (super.noSuchMethod(
            Invocation.method(#saveWeight, [weight]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<List<_i21.Weight>> getWeightsForRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getWeightsForRange, [start, end]),
            returnValue: _i13.Future<List<_i21.Weight>>.value(<_i21.Weight>[]),
          )
          as _i13.Future<List<_i21.Weight>>);

  @override
  _i13.Future<void> deleteWeight(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWeight, [id]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<List<_i22.FoodContainer>> getAllContainers() =>
      (super.noSuchMethod(
            Invocation.method(#getAllContainers, []),
            returnValue: _i13.Future<List<_i22.FoodContainer>>.value(
              <_i22.FoodContainer>[],
            ),
          )
          as _i13.Future<List<_i22.FoodContainer>>);

  @override
  _i13.Future<int> saveContainer(_i22.FoodContainer? container) =>
      (super.noSuchMethod(
            Invocation.method(#saveContainer, [container]),
            returnValue: _i13.Future<int>.value(0),
          )
          as _i13.Future<int>);

  @override
  _i13.Future<void> deleteContainer(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteContainer, [id]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<bool> isFastedOnDate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#isFastedOnDate, [date]),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  _i13.Future<void> toggleFasted(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFasted, [date]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> updateLoggedPortionsTimestamp(
    List<int>? loggedPortionIds,
    DateTime? newTimestamp,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateLoggedPortionsTimestamp, [
              loggedPortionIds,
              newTimestamp,
            ]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<List<_i2.LoggedMacroDTO>> getLoggedMacrosForDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLoggedMacrosForDateRange, [start, end]),
            returnValue: _i13.Future<List<_i2.LoggedMacroDTO>>.value(
              <_i2.LoggedMacroDTO>[],
            ),
          )
          as _i13.Future<List<_i2.LoggedMacroDTO>>);

  @override
  _i13.Future<_i7.Food?> getFoodById(int? id, String? source) =>
      (super.noSuchMethod(
            Invocation.method(#getFoodById, [id, source]),
            returnValue: _i13.Future<_i7.Food?>.value(),
          )
          as _i13.Future<_i7.Food?>);

  @override
  _i13.Future<Map<int, _i7.Food>> getFoodsByIds(
    List<int>? ids,
    String? source,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFoodsByIds, [ids, source]),
            returnValue: _i13.Future<Map<int, _i7.Food>>.value(
              <int, _i7.Food>{},
            ),
          )
          as _i13.Future<Map<int, _i7.Food>>);

  @override
  _i13.Future<Map<int, _i6.Recipe>> getRecipesByIds(List<int>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#getRecipesByIds, [ids]),
            returnValue: _i13.Future<Map<int, _i6.Recipe>>.value(
              <int, _i6.Recipe>{},
            ),
          )
          as _i13.Future<Map<int, _i6.Recipe>>);

  @override
  _i13.Future<List<_i6.Recipe>> getRecipes({bool? includeHidden = false}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecipes, [], {#includeHidden: includeHidden}),
            returnValue: _i13.Future<List<_i6.Recipe>>.value(<_i6.Recipe>[]),
          )
          as _i13.Future<List<_i6.Recipe>>);

  @override
  _i13.Future<List<_i6.Recipe>> getRecipesBySearch(
    String? query, {
    int? categoryId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getRecipesBySearch,
              [query],
              {#categoryId: categoryId},
            ),
            returnValue: _i13.Future<List<_i6.Recipe>>.value(<_i6.Recipe>[]),
          )
          as _i13.Future<List<_i6.Recipe>>);

  @override
  _i13.Future<_i6.Recipe> getRecipeById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getRecipeById, [id]),
            returnValue: _i13.Future<_i6.Recipe>.value(
              _FakeRecipe_4(this, Invocation.method(#getRecipeById, [id])),
            ),
          )
          as _i13.Future<_i6.Recipe>);

  @override
  _i13.Future<List<_i23.Category>> getCategoriesForRecipe(int? recipeId) =>
      (super.noSuchMethod(
            Invocation.method(#getCategoriesForRecipe, [recipeId]),
            returnValue: _i13.Future<List<_i23.Category>>.value(
              <_i23.Category>[],
            ),
          )
          as _i13.Future<List<_i23.Category>>);

  @override
  _i13.Future<int> saveRecipe(_i6.Recipe? recipe) =>
      (super.noSuchMethod(
            Invocation.method(#saveRecipe, [recipe]),
            returnValue: _i13.Future<int>.value(0),
          )
          as _i13.Future<int>);

  @override
  _i13.Future<void> deleteRecipe(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRecipe, [id]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<List<_i23.Category>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i13.Future<List<_i23.Category>>.value(
              <_i23.Category>[],
            ),
          )
          as _i13.Future<List<_i23.Category>>);

  @override
  _i13.Future<int> addCategory(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#addCategory, [name]),
            returnValue: _i13.Future<int>.value(0),
          )
          as _i13.Future<int>);

  @override
  _i13.Future<_i7.Food> ensureFoodExists(_i7.Food? food) =>
      (super.noSuchMethod(
            Invocation.method(#ensureFoodExists, [food]),
            returnValue: _i13.Future<_i7.Food>.value(
              _FakeFood_5(this, Invocation.method(#ensureFoodExists, [food])),
            ),
          )
          as _i13.Future<_i7.Food>);

  @override
  _i13.Future<Map<int, String?>> getFoodsUsageNotes(List<_i7.Food>? foods) =>
      (super.noSuchMethod(
            Invocation.method(#getFoodsUsageNotes, [foods]),
            returnValue: _i13.Future<Map<int, String?>>.value(<int, String?>{}),
          )
          as _i13.Future<Map<int, String?>>);

  @override
  _i13.Future<_i7.Food> copyFoodToLiveDb(
    _i7.Food? sourceFood, {
    bool? isCopy = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #copyFoodToLiveDb,
              [sourceFood],
              {#isCopy: isCopy},
            ),
            returnValue: _i13.Future<_i7.Food>.value(
              _FakeFood_5(
                this,
                Invocation.method(
                  #copyFoodToLiveDb,
                  [sourceFood],
                  {#isCopy: isCopy},
                ),
              ),
            ),
          )
          as _i13.Future<_i7.Food>);

  @override
  _i13.Future<void> softDeleteFood(int? foodId, String? source) =>
      (super.noSuchMethod(
            Invocation.method(#softDeleteFood, [foodId, source]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<bool> isFoodReferenced(int? foodId, String? source) =>
      (super.noSuchMethod(
            Invocation.method(#isFoodReferenced, [foodId, source]),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  _i13.Future<void> deleteFood(int? foodId, String? source) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFood, [foodId, source]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<List<_i7.Food>> searchLiveFoodsByName(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchLiveFoodsByName, [query]),
            returnValue: _i13.Future<List<_i7.Food>>.value(<_i7.Food>[]),
          )
          as _i13.Future<List<_i7.Food>>);

  @override
  _i13.Future<List<_i7.Food>> searchReferenceFoodsByName(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchReferenceFoodsByName, [query]),
            returnValue: _i13.Future<List<_i7.Food>>.value(<_i7.Food>[]),
          )
          as _i13.Future<List<_i7.Food>>);

  @override
  _i13.Future<Map<int, _i24.FoodUsageStats>> getFoodUsageStats(
    List<int>? foodIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFoodUsageStats, [foodIds]),
            returnValue: _i13.Future<Map<int, _i24.FoodUsageStats>>.value(
              <int, _i24.FoodUsageStats>{},
            ),
          )
          as _i13.Future<Map<int, _i24.FoodUsageStats>>);

  @override
  _i13.Future<Map<int, _i24.FoodUsageStats>> getRecipeUsageStats(
    List<int>? recipeIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getRecipeUsageStats, [recipeIds]),
            returnValue: _i13.Future<Map<int, _i24.FoodUsageStats>>.value(
              <int, _i24.FoodUsageStats>{},
            ),
          )
          as _i13.Future<Map<int, _i24.FoodUsageStats>>);

  @override
  _i13.Future<bool> isRecipeReferenced(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#isRecipeReferenced, [id]),
            returnValue: _i13.Future<bool>.value(false),
          )
          as _i13.Future<bool>);

  @override
  _i13.Future<List<_i7.Food>> filterReferenceFoodsWithLiveVersions(
    List<_i7.Food>? referenceFoods,
    List<_i7.Food>? liveFoods,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#filterReferenceFoodsWithLiveVersions, [
              referenceFoods,
              liveFoods,
            ]),
            returnValue: _i13.Future<List<_i7.Food>>.value(<_i7.Food>[]),
          )
          as _i13.Future<List<_i7.Food>>);
}

/// A class which mocks [GoalsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoalsProvider extends _i1.Mock implements _i25.GoalsProvider {
  MockGoalsProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.GoalSettings get settings =>
      (super.noSuchMethod(
            Invocation.getter(#settings),
            returnValue: _FakeGoalSettings_6(
              this,
              Invocation.getter(#settings),
            ),
          )
          as _i8.GoalSettings);

  @override
  _i9.MacroGoals get currentGoals =>
      (super.noSuchMethod(
            Invocation.getter(#currentGoals),
            returnValue: _FakeMacroGoals_7(
              this,
              Invocation.getter(#currentGoals),
            ),
          )
          as _i9.MacroGoals);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get showUpdateNotification =>
      (super.noSuchMethod(
            Invocation.getter(#showUpdateNotification),
            returnValue: false,
          )
          as bool);

  @override
  bool get isGoalsSet =>
      (super.noSuchMethod(Invocation.getter(#isGoalsSet), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void dismissNotification() => super.noSuchMethod(
    Invocation.method(#dismissNotification, []),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Future<void> saveSettings(
    _i8.GoalSettings? newSettings, {
    bool? isInitialSetup = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #saveSettings,
              [newSettings],
              {#isInitialSetup: isInitialSetup},
            ),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> checkWeeklyUpdate() =>
      (super.noSuchMethod(
            Invocation.method(#checkWeeklyUpdate, []),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> recalculateTargets({bool? isInitialSetup = false}) =>
      (super.noSuchMethod(
            Invocation.method(#recalculateTargets, [], {
              #isInitialSetup: isInitialSetup,
            }),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [WeightProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeightProvider extends _i1.Mock implements _i26.WeightProvider {
  MockWeightProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i21.Weight> get weights =>
      (super.noSuchMethod(
            Invocation.getter(#weights),
            returnValue: <_i21.Weight>[],
          )
          as List<_i21.Weight>);

  @override
  List<_i21.Weight> get recentWeights =>
      (super.noSuchMethod(
            Invocation.getter(#recentWeights),
            returnValue: <_i21.Weight>[],
          )
          as List<_i21.Weight>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasWeightToday =>
      (super.noSuchMethod(
            Invocation.getter(#hasWeightToday),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i21.Weight? getWeightForDate(DateTime? date) =>
      (super.noSuchMethod(Invocation.method(#getWeightForDate, [date]))
          as _i21.Weight?);

  @override
  _i13.Future<void> loadWeights(DateTime? start, DateTime? end) =>
      (super.noSuchMethod(
            Invocation.method(#loadWeights, [start, end]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> saveWeight(double? value, DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#saveWeight, [value, date]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  _i13.Future<void> deleteWeight(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWeight, [id]),
            returnValue: _i13.Future<void>.value(),
            returnValueForMissingStub: _i13.Future<void>.value(),
          )
          as _i13.Future<void>);

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
