// Mocks generated by Mockito 5.4.6 from annotations
// in free_cal_counter1/test/screens/overview_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i9;

import 'package:free_cal_counter1/models/food.dart' as _i12;
import 'package:free_cal_counter1/models/daily_macro_stats.dart' as _i13;
import 'package:free_cal_counter1/models/food_portion.dart' as _i6;
import 'package:free_cal_counter1/models/logged_food.dart' as _i7;
import 'package:free_cal_counter1/providers/food_search_provider.dart' as _i11;
import 'package:free_cal_counter1/providers/log_provider.dart' as _i5;
import 'package:free_cal_counter1/providers/navigation_provider.dart' as _i10;
import 'package:free_cal_counter1/services/database_service.dart' as _i2;
import 'package:free_cal_counter1/services/food_search_service.dart' as _i4;
import 'package:free_cal_counter1/services/open_food_facts_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabaseService_0 extends _i1.SmartFake
    implements _i2.DatabaseService {
  _FakeDatabaseService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOffApiService_1 extends _i1.SmartFake implements _i3.OffApiService {
  _FakeOffApiService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFoodSearchService_2 extends _i1.SmartFake
    implements _i4.FoodSearchService {
  _FakeFoodSearchService_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDailyMacroStats_3 extends _i1.SmartFake
    implements _i13.DailyMacroStats {
  _FakeDailyMacroStats_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LogProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogProvider extends _i1.Mock implements _i5.LogProvider {
  MockLogProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  double get loggedCalories =>
      (super.noSuchMethod(Invocation.getter(#loggedCalories), returnValue: 0.0)
          as double);

  @override
  double get queuedCalories =>
      (super.noSuchMethod(Invocation.getter(#queuedCalories), returnValue: 0.0)
          as double);

  @override
  double get totalCalories =>
      (super.noSuchMethod(Invocation.getter(#totalCalories), returnValue: 0.0)
          as double);

  @override
  double get dailyTargetCalories =>
      (super.noSuchMethod(
            Invocation.getter(#dailyTargetCalories),
            returnValue: 0.0,
          )
          as double);

  @override
  List<_i6.FoodPortion> get logQueue =>
      (super.noSuchMethod(
            Invocation.getter(#logQueue),
            returnValue: <_i6.FoodPortion>[],
          )
          as List<_i6.FoodPortion>);

  @override
  List<_i7.LoggedFood> get loggedFoods =>
      (super.noSuchMethod(
            Invocation.getter(#loggedFoods),
            returnValue: <_i7.LoggedFood>[],
          )
          as List<_i7.LoggedFood>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i8.Future<List<_i13.DailyMacroStats>> getDailyMacroStats(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getDailyMacroStats, [start, end]),
            returnValue: _i8.Future<List<_i13.DailyMacroStats>>.value(
              <_i13.DailyMacroStats>[],
            ),
          )
          as _i8.Future<List<_i13.DailyMacroStats>>);

  @override
  _i8.Future<_i13.DailyMacroStats> getTodayStats() =>
      (super.noSuchMethod(
            Invocation.method(#getTodayStats, []),
            returnValue: _i8.Future<_i13.DailyMacroStats>.value(
              _FakeDailyMacroStats_3(
                this,
                Invocation.method(#getTodayStats, []),
              ),
            ),
          )
          as _i8.Future<_i13.DailyMacroStats>);

  @override
  void addFoodToQueue(_i6.FoodPortion? serving) => super.noSuchMethod(
    Invocation.method(#addFoodToQueue, [serving]),
    returnValueForMissingStub: null,
  );

  @override
  void updateFoodInQueue(int? index, _i6.FoodPortion? newPortion) =>
      super.noSuchMethod(
        Invocation.method(#updateFoodInQueue, [index, newPortion]),
        returnValueForMissingStub: null,
      );

  @override
  void removeFoodFromQueue(_i6.FoodPortion? serving) => super.noSuchMethod(
    Invocation.method(#removeFoodFromQueue, [serving]),
    returnValueForMissingStub: null,
  );

  @override
  void clearQueue() => super.noSuchMethod(
    Invocation.method(#clearQueue, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> logQueueToDatabase() =>
      (super.noSuchMethod(
            Invocation.method(#logQueueToDatabase, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> loadLoggedFoodsForDate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#loadLoggedFoodsForDate, [date]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteLoggedFood(_i7.LoggedFood? food) =>
      (super.noSuchMethod(
            Invocation.method(#deleteLoggedFood, [food]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NavigationProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationProvider extends _i1.Mock
    implements _i10.NavigationProvider {
  MockNavigationProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get selectedIndex =>
      (super.noSuchMethod(Invocation.getter(#selectedIndex), returnValue: 0)
          as int);

  @override
  bool get shouldFocusSearch =>
      (super.noSuchMethod(
            Invocation.getter(#shouldFocusSearch),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void changeTab(int? index) => super.noSuchMethod(
    Invocation.method(#changeTab, [index]),
    returnValueForMissingStub: null,
  );

  @override
  void goToFoodSearch() => super.noSuchMethod(
    Invocation.method(#goToFoodSearch, []),
    returnValueForMissingStub: null,
  );

  @override
  void resetSearchFocus() => super.noSuchMethod(
    Invocation.method(#resetSearchFocus, []),
    returnValueForMissingStub: null,
  );

  @override
  void goBack() => super.noSuchMethod(
    Invocation.method(#goBack, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [FoodSearchProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockFoodSearchProvider extends _i1.Mock
    implements _i11.FoodSearchProvider {
  MockFoodSearchProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseService get databaseService =>
      (super.noSuchMethod(
            Invocation.getter(#databaseService),
            returnValue: _FakeDatabaseService_0(
              this,
              Invocation.getter(#databaseService),
            ),
          )
          as _i2.DatabaseService);

  @override
  _i3.OffApiService get offApiService =>
      (super.noSuchMethod(
            Invocation.getter(#offApiService),
            returnValue: _FakeOffApiService_1(
              this,
              Invocation.getter(#offApiService),
            ),
          )
          as _i3.OffApiService);

  @override
  _i4.FoodSearchService get foodSearchService =>
      (super.noSuchMethod(
            Invocation.getter(#foodSearchService),
            returnValue: _FakeFoodSearchService_2(
              this,
              Invocation.getter(#foodSearchService),
            ),
          )
          as _i4.FoodSearchService);

  @override
  List<_i12.Food> get searchResults =>
      (super.noSuchMethod(
            Invocation.getter(#searchResults),
            returnValue: <_i12.Food>[],
          )
          as List<_i12.Food>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i8.Future<void> textSearch(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#textSearch, [query]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> performOffSearch() =>
      (super.noSuchMethod(
            Invocation.method(#performOffSearch, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> barcodeSearch(String? barcode) =>
      (super.noSuchMethod(
            Invocation.method(#barcodeSearch, [barcode]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
