// Mocks generated by Mockito 5.4.6 from annotations
// in free_cal_counter1/test/screens/weight_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i7;

import 'package:free_cal_counter1/models/goal_settings.dart' as _i2;
import 'package:free_cal_counter1/models/macro_goals.dart' as _i3;
import 'package:free_cal_counter1/models/weight.dart' as _i5;
import 'package:free_cal_counter1/providers/goals_provider.dart' as _i8;
import 'package:free_cal_counter1/providers/navigation_provider.dart' as _i9;
import 'package:free_cal_counter1/providers/weight_provider.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGoalSettings_0 extends _i1.SmartFake implements _i2.GoalSettings {
  _FakeGoalSettings_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMacroGoals_1 extends _i1.SmartFake implements _i3.MacroGoals {
  _FakeMacroGoals_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WeightProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeightProvider extends _i1.Mock implements _i4.WeightProvider {
  MockWeightProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i5.Weight> get weights =>
      (super.noSuchMethod(
            Invocation.getter(#weights),
            returnValue: <_i5.Weight>[],
          )
          as List<_i5.Weight>);

  @override
  List<_i5.Weight> get recentWeights =>
      (super.noSuchMethod(
            Invocation.getter(#recentWeights),
            returnValue: <_i5.Weight>[],
          )
          as List<_i5.Weight>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasWeightToday =>
      (super.noSuchMethod(
            Invocation.getter(#hasWeightToday),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Weight? getWeightForDate(DateTime? date) =>
      (super.noSuchMethod(Invocation.method(#getWeightForDate, [date]))
          as _i5.Weight?);

  @override
  _i6.Future<void> loadWeights(DateTime? start, DateTime? end) =>
      (super.noSuchMethod(
            Invocation.method(#loadWeights, [start, end]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> saveWeight(double? value, DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#saveWeight, [value, date]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteWeight(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteWeight, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [GoalsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoalsProvider extends _i1.Mock implements _i8.GoalsProvider {
  MockGoalsProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GoalSettings get settings =>
      (super.noSuchMethod(
            Invocation.getter(#settings),
            returnValue: _FakeGoalSettings_0(
              this,
              Invocation.getter(#settings),
            ),
          )
          as _i2.GoalSettings);

  @override
  _i3.MacroGoals get currentGoals =>
      (super.noSuchMethod(
            Invocation.getter(#currentGoals),
            returnValue: _FakeMacroGoals_1(
              this,
              Invocation.getter(#currentGoals),
            ),
          )
          as _i3.MacroGoals);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get showUpdateNotification =>
      (super.noSuchMethod(
            Invocation.getter(#showUpdateNotification),
            returnValue: false,
          )
          as bool);

  @override
  bool get isGoalsSet =>
      (super.noSuchMethod(Invocation.getter(#isGoalsSet), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void dismissNotification() => super.noSuchMethod(
    Invocation.method(#dismissNotification, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> saveSettings(_i2.GoalSettings? newSettings) =>
      (super.noSuchMethod(
            Invocation.method(#saveSettings, [newSettings]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> checkWeeklyUpdate() =>
      (super.noSuchMethod(
            Invocation.method(#checkWeeklyUpdate, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> recalculateTargets() =>
      (super.noSuchMethod(
            Invocation.method(#recalculateTargets, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NavigationProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationProvider extends _i1.Mock
    implements _i9.NavigationProvider {
  MockNavigationProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get selectedIndex =>
      (super.noSuchMethod(Invocation.getter(#selectedIndex), returnValue: 0)
          as int);

  @override
  bool get shouldFocusSearch =>
      (super.noSuchMethod(
            Invocation.getter(#shouldFocusSearch),
            returnValue: false,
          )
          as bool);

  @override
  bool get showConsumed =>
      (super.noSuchMethod(Invocation.getter(#showConsumed), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setShowConsumed(bool? value) => super.noSuchMethod(
    Invocation.method(#setShowConsumed, [value]),
    returnValueForMissingStub: null,
  );

  @override
  void changeTab(int? index) => super.noSuchMethod(
    Invocation.method(#changeTab, [index]),
    returnValueForMissingStub: null,
  );

  @override
  void goToSearch() => super.noSuchMethod(
    Invocation.method(#goToSearch, []),
    returnValueForMissingStub: null,
  );

  @override
  void goToDataManagement() => super.noSuchMethod(
    Invocation.method(#goToDataManagement, []),
    returnValueForMissingStub: null,
  );

  @override
  void resetSearchFocus() => super.noSuchMethod(
    Invocation.method(#resetSearchFocus, []),
    returnValueForMissingStub: null,
  );

  @override
  void goBack() => super.noSuchMethod(
    Invocation.method(#goBack, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
