const Map<String, String> foodEmojiMap = {
  // Fruits
  'apple': '🍎',
  'green apple': '🍏',
  'banana': '🍌',
  'strawberry': '🍓',
  'orange': '🍊',
  'lemon': '🍋',
  'lime': '🍋',
  'cherry': '🍒',
  'peach': '🍑',
  'pear': '🍐',
  'grape': '🍇',
  'watermelon': '🍉',
  'melon': '🍈',
  'cantaloupe': '🍈',
  'honeydew': '🍈',
  'pineapple': '🍍',
  'mango': '🥭',
  'kiwi': '🥝',
  'blueberry': '🫐',
  'blackberry': '🫐',
  'avocado': '🥑',
  'tomato': '🍅',
  'coconut': '🥥',
  'olive': '🫒',

  // Vegetables
  'lettuce': '🥬',
  'spinach': '🥬',
  'kale': '🥬',
  'cabbage': '🥬',
  'broccoli': '🥦',
  'cauliflower': '🥦',
  'brussels sprouts': '🥦',
  'carrot': '🥕',
  'beet': '🥕',
  'radish': '🥕',
  'potato': '🥔',
  'sweet potato': '🥔',
  'onion': '🧅',
  'scallion': '🧅',
  'garlic': '🧄',
  'cucumber': '🥒',
  'zucchini': '🥒',
  'pickle': '🥒',
  'eggplant': '🍆',
  'bell pepper': '🫑',
  'jalapeno': '🌶️',
  'chili pepper': '🌶️',
  'corn': '🌽',
  'peas': '🫛',
  'green bean': '🫛',
  'mushroom': '🍄',
  'asparagus': '🌱',
  'celery': '🌱',
  'artichoke': '🥬',

  // Proteins
  'chicken': '🍗',
  'turkey': '🍗',
  'duck': '🍗',
  'beef': '🥩',
  'pork': '🥓',
  'bacon': '🥓',
  'ham': '🥓',
  'sausage': '🌭',
  'hot dog': '🌭',
  'fish': '🐟',
  'salmon': '🐟',
  'tuna': '🐟',
  'shrimp': '🦐',
  'crab': '🦐',
  'lobster': '🦐',
  'clam': '🦪',
  'oyster': '🦪',
  'egg': '🥚',
  'tofu': '🥢',
  'tempeh': '🥢',
  'seitan': '🥢',

  // Dairy
  'milk': '🥛',
  'cheese': '🧀',
  'yogurt': '🥛',
  'butter': '🧈',
  'cream': '🥛',
  'ice cream': '🍨',

  // Grains & Carbs
  'bread': '🍞',
  'roll': '🥖',
  'bagel': '🥯',
  'croissant': '🥐',
  'pita': '🌯',
  'tortilla': '🌮',
  'rice': '🍚',
  'noodles': '🍜',
  'pasta': '🍝',
  'cereal': '🥣',
  'cornbread': '🌽',
  'waffle': '🧇',
  'pancake': '🥞',
  'pretzel': '🥨',
  'popcorn': '🍿',
  'cracker': '🍞',
  'chip': '🥔',
  'french fries': '🍟',

  // Nuts & Seeds
  'nut': '🥜',
  'peanut': '🥜',
  'almond': '🥜',
  'walnut': '🥜',
  'pistachio': '🥜',
  'cashew': '🥜',
  'sunflower seed': '🥜',
  'pumpkin seed': '🥜',
  'chia seed': '🌱',
  'flax seed': '🌱',

  // Sweets & Snacks
  'chocolate': '🍫',
  'cookie': '🍪',
  'cake': '🍰',
  'cupcake': '🧁',
  'donut': '🍩',
  'pie': '🥧',
  'brownie': '🍪',
  'candy': '🍭',
  'lollipop': '🍭',
  'marshmallow': '🍬',
  'caramel': '🍮',

  // Beverages
  'water': '💧',
  'juice': '🧃',
  'soda': '🥤',
  'coffee': '☕',
  'espresso': '☕',
  'latte': '☕',
  'cappuccino': '☕',
  'tea': '🍵',
  'green tea': '🍵',
  'black tea': '🍵',
  'beer': '🍺',
  'wine': '🍷',
  'cocktail': '🍹',
  'whiskey': '🥃',

  // Prepared Foods
  'pizza': '🍕',
  'burger': '🍔',
  'sandwich': '🥪',
  'taco': '🌮',
  'burrito': '🌯',
  'sushi': '🍣',
  'tuna roll': '🍣',
  'avocado roll': '🍣',
  'california roll': '🍣',
  'salad': '🥗',
  'soup': '🍲',
  'stew': '🥘',
  'curry': '🥘',
  'omelet': '🥚',
  'fries': '🍟',
  'nachos': '🌮',
  'dumpling': '🥟',
  'spring roll': '🥢',
};
